Repository rotki/rotki, pull requests merged in 2022-09, with the labels that each got.

#4768 use unix timestamp for generic trades import
  rotkehlchen/data_import/importers/rotki_trades.py
  rotkehlchen/tests/api/test_data_import.py
  rotkehlchen/tests/data/rotki_generic_trades.csv
  rotkehlchen/tests/utils/dataimport.py
Labels: ready for final review

#4736 Ensure xpubs are blockchain-specific
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/fields.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/chain/bitcoin/xpub.py
  rotkehlchen/chain/manager.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/upgrades/v34_v35.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tests/api/test_bitcoin.py
  rotkehlchen/tests/api/test_blockchain.py
  rotkehlchen/tests/data/remote_old_encrypted_db.txt
  rotkehlchen/tests/data/v34_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/db/test_xpubs.py
  rotkehlchen/tests/unit/test_bitcoin.py
  rotkehlchen/tests/unit/test_tasks_manager.py
  rotkehlchen/types.py
  rotkehlchen/utils/mixins/serializableenumvalue.py
Labels: ready for final review

#4767 allow mass deletion of trades & ledger actions
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/ledger_actions.py
  rotkehlchen/tests/api/test_ledger_actions.py
  rotkehlchen/tests/api/test_trades.py
  rotkehlchen/tests/unit/test_globaldb.py
  rotkehlchen/tests/unit/test_ledger_actions.py
Labels: ready for final review

#4764 Adjust globaldb v3 schema
  docs/changelog.rst
  rotkehlchen/api/rest.py
  rotkehlchen/assets/asset.py
  rotkehlchen/data/global.db
  rotkehlchen/data/globaldb_v2_v3_assets.sql
  rotkehlchen/db/dbhandler.py
  rotkehlchen/globaldb/handler.py
  rotkehlchen/globaldb/schema.py
  rotkehlchen/globaldb/updates.py
  rotkehlchen/globaldb/upgrades/v2_v3.py
  rotkehlchen/tests/api/test_assets_updates.py
  rotkehlchen/tests/api/test_user_assets.py
  rotkehlchen/tests/api/test_user_ethereum_tokens.py
  rotkehlchen/tests/fixtures/assets.py
  rotkehlchen/tests/fixtures/globaldb.py
  rotkehlchen/tests/unit/test_globaldb.py
  rotkehlchen/tests/unit/test_globaldb_upgrades.py
  rotkehlchen/tests/utils/dataimport.py
  rotkehlchen/tests/utils/globaldb.py
Labels: ready for final review

#4741 Support multiple blockchains in web3_nodes table
  docs/api.rst
  docs/usage_guide.rst
  frontend/app/src/types/settings.ts
  rotkehlchen/api/rest.py
  rotkehlchen/api/server.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/chain/ethereum/constants.py
  rotkehlchen/chain/ethereum/defi/zerionsdk.py
  rotkehlchen/chain/ethereum/manager.py
  rotkehlchen/chain/ethereum/types.py
  rotkehlchen/chain/manager.py
  rotkehlchen/data/nodes.json
  rotkehlchen/data_migrations/migrations/migration_4.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/upgrades/v34_v35.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/api/test_blockchain.py
  rotkehlchen/tests/api/test_misc.py
  rotkehlchen/tests/api/test_uniswap.py
  rotkehlchen/tests/api/test_yearn_vaults.py
  rotkehlchen/tests/data/v34_rotkehlchen.db
  rotkehlchen/tests/data_migrations/test_migrations.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/unit/test_ethereum_manager.py
  rotkehlchen/tests/utils/constants.py
  rotkehlchen/tests/utils/ethereum.py
  tools/uniswapv2/detect.py
Labels: PR review work

#4786 Move name from common_assets_details to asset table
  rotkehlchen/data/global.db
  rotkehlchen/data/globaldb_v2_v3_assets.sql
  rotkehlchen/globaldb/handler.py
  rotkehlchen/globaldb/schema.py
  rotkehlchen/globaldb/updates.py
  rotkehlchen/globaldb/upgrades/v2_v3.py
  rotkehlchen/tests/api/test_assets_updates.py
  rotkehlchen/tests/unit/test_globaldb.py
  rotkehlchen/tests/unit/test_globaldb_asset_updates.py
  rotkehlchen/tests/unit/test_globaldb_upgrades.py
Labels: ready for final review

#4800 Generalize EthTokens class
  rotkehlchen/api/rest.py
  rotkehlchen/chain/evm/tokens.py
  rotkehlchen/chain/manager.py
  rotkehlchen/tests/api/test_balances.py
  rotkehlchen/tests/integration/test_blockchain.py
  rotkehlchen/tests/unit/test_tokens.py
  rotkehlchen/tests/utils/rotkehlchen.py
  tools/scripts/generate_constant_assets.py
Labels: ready for final review

#4812 add collection name as fallback name for nft balances
  docs/api.rst
  rotkehlchen/chain/ethereum/modules/nfts.py
  rotkehlchen/tests/api/test_nfts.py
Labels: ready for final review

#4814 db upgrade for ignored assets to caip format
  rotkehlchen/db/upgrades/v34_v35.py
  rotkehlchen/tests/data/v34_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
Labels: ready for final review

#4819 Fix pool_tokens key in balancer API response
  rotkehlchen/chain/ethereum/modules/balancer/types.py
  rotkehlchen/tests/api/test_balancer.py
Labels: ready for final review

#4836 Update generate constant assets script
  tools/scripts/generate_constant_assets.py
Labels: ready for final review

#4826 Remove chaind enum
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/assets/asset.py
  rotkehlchen/assets/spam_assets.py
  rotkehlchen/assets/types.py
  rotkehlchen/assets/utils.py
  rotkehlchen/chain/constants.py
  rotkehlchen/chain/ethereum/decoding/decoder.py
  rotkehlchen/chain/ethereum/interfaces/ammswap/ammswap.py
  rotkehlchen/chain/ethereum/interfaces/ammswap/utils.py
  rotkehlchen/chain/ethereum/manager.py
  rotkehlchen/chain/ethereum/modules/aave/common.py
  rotkehlchen/chain/ethereum/modules/balancer/balancer.py
  rotkehlchen/chain/ethereum/modules/balancer/utils.py
  rotkehlchen/chain/ethereum/modules/curve/pools_cache.py
  rotkehlchen/chain/ethereum/modules/uniswap/v3/utils.py
  rotkehlchen/chain/evm/tokens.py
  rotkehlchen/constants/assets.py
  rotkehlchen/constants/assets.py.template
  rotkehlchen/constants/ethereum.py
  rotkehlchen/constants/resolver.py
  rotkehlchen/data/global.db
  rotkehlchen/data/globaldb_v2_v3_assets.sql
  rotkehlchen/db/schema.py
  rotkehlchen/db/upgrades/v34_v35.py
  rotkehlchen/globaldb/handler.py
  rotkehlchen/globaldb/schema.py
  rotkehlchen/globaldb/updates.py
  rotkehlchen/globaldb/upgrades/v2_v3.py
  rotkehlchen/inquirer.py
  rotkehlchen/serialization/serialize.py
  rotkehlchen/tests/api/test_assets_updates.py
  rotkehlchen/tests/api/test_balancer.py
  rotkehlchen/tests/api/test_user_ethereum_tokens.py
  rotkehlchen/tests/unit/test_assets.py
  rotkehlchen/tests/unit/test_general_cache.py
  rotkehlchen/tests/unit/test_globaldb.py
  rotkehlchen/tests/unit/test_globaldb_asset_updates.py
  rotkehlchen/tests/unit/test_globaldb_upgrades.py
  rotkehlchen/tests/unit/test_inquirer.py
  rotkehlchen/tests/utils/blockchain.py
  rotkehlchen/tests/utils/globaldb.py
  rotkehlchen/types.py
Labels: ready for final review

#4843 Add manual current price support on backend
  frontend/app/src/components/settings/OracleEntry.vue
  frontend/app/src/components/settings/PriceOracleSettings.vue
  frontend/app/src/locales/en.json
  frontend/app/src/locales/gr.json
  frontend/app/src/types/user.ts
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/db/upgrades/v34_v35.py
  rotkehlchen/globaldb/handler.py
  rotkehlchen/globaldb/manual_price_oracle.py
  rotkehlchen/globaldb/manual_price_oracles.py
  rotkehlchen/globaldb/schema.py
  rotkehlchen/globaldb/upgrades/v2_v3.py
  rotkehlchen/history/price.py
  rotkehlchen/history/types.py
  rotkehlchen/inquirer.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/api/test_balances.py
  rotkehlchen/tests/api/test_current_assets_price.py
  rotkehlchen/tests/data/v34_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/fixtures/accounting.py
  rotkehlchen/tests/unit/test_price_historian.py
  rotkehlchen/tests/utils/rotkehlchen.py
  rotkehlchen/user_messages.py
Labels: ready for final review

#4859 Make sure that evm assets manually added are used in all the tables
  rotkehlchen/globaldb/upgrades/v2_v3.py
  rotkehlchen/tests/data/v2_global.db
  rotkehlchen/tests/unit/test_globaldb_upgrades.py
Labels: ready for final review

#4898 Improve Assets Endpoints
  docs/api.rst
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/filtering.py
  rotkehlchen/globaldb/handler.py
  rotkehlchen/tests/api/test_assets.py
Labels: ready for peer review
