Repository rotki/rotki, pull requests merged in 2022-08, with the labels that each got.

#4642 Migrates defi vuex store to pinia
  frontend/app/src/components/defi/Borrowing.vue
  frontend/app/src/components/defi/DepositProtocolReset.vue
  frontend/app/src/components/defi/DepositTotals.vue
  frontend/app/src/components/defi/Deposits.vue
  frontend/app/src/components/defi/balancer/Balancer.vue
  frontend/app/src/components/defi/dex-trades/DexTradeHistory.vue
  frontend/app/src/components/defi/yearn/YearnAssetsTable.vue
  frontend/app/src/components/helper/DefiProtocolSelector.vue
  frontend/app/src/composables/defi.ts
  frontend/app/src/composables/session.ts
  frontend/app/src/premium/premium-apis.ts
  frontend/app/src/store/balances/actions.ts
  frontend/app/src/store/defi/aave/index.ts
  frontend/app/src/store/defi/actions.ts
  frontend/app/src/store/defi/balancer/index.ts
  frontend/app/src/store/defi/compound/index.ts
  frontend/app/src/store/defi/const.ts
  frontend/app/src/store/defi/converters.ts
  frontend/app/src/store/defi/getters.ts
  frontend/app/src/store/defi/index.ts
  frontend/app/src/store/defi/liquity/index.ts
  frontend/app/src/store/defi/makerdao/index.ts
  frontend/app/src/store/defi/mutation-types.ts
  frontend/app/src/store/defi/mutations.ts
  frontend/app/src/store/defi/protocols/index.ts
  frontend/app/src/store/defi/state.ts
  frontend/app/src/store/defi/sushiswap/index.ts
  frontend/app/src/store/defi/trades/index.ts
  frontend/app/src/store/defi/types.ts
  frontend/app/src/store/defi/uniswap.ts
  frontend/app/src/store/defi/yearn/index.ts
  frontend/app/src/store/session/actions.ts
  frontend/app/src/store/store.ts
  frontend/app/src/views/defi/Airdrops.vue
  frontend/app/src/views/defi/DecentralizedBorrowing.vue
  frontend/app/src/views/defi/DecentralizedOverview.vue
  frontend/common/src/defi/balancer/index.ts
Labels: refactor

#4714 add support for taproot btc
  docs/api.rst
  requirements.txt
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/chain/bitcoin/hdkey.py
  rotkehlchen/chain/bitcoin/utils.py
  rotkehlchen/tests/api/test_bitcoin.py
  rotkehlchen/tests/api/test_blockchain.py
  rotkehlchen/tests/unit/test_bitcoin.py
Labels: ready for final review

#4727 Balances removal follow up
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/chain/ethereum/defi/defisaver_proxy.py
  rotkehlchen/chain/ethereum/modules/aave/aave.py
  rotkehlchen/chain/ethereum/modules/adex/adex.py
  rotkehlchen/chain/ethereum/modules/balancer/balancer.py
  rotkehlchen/chain/ethereum/modules/compound/compound.py
  rotkehlchen/chain/ethereum/modules/eth2/eth2.py
  rotkehlchen/chain/ethereum/modules/l2/loopring.py
  rotkehlchen/chain/ethereum/modules/liquity/trove.py
  rotkehlchen/chain/ethereum/modules/makerdao/vaults.py
  rotkehlchen/chain/ethereum/modules/nfts.py
  rotkehlchen/chain/ethereum/modules/pickle_finance/main.py
  rotkehlchen/chain/ethereum/modules/sushiswap/sushiswap.py
  rotkehlchen/chain/ethereum/modules/uniswap/uniswap.py
  rotkehlchen/chain/ethereum/modules/yearn/vaults.py
  rotkehlchen/chain/manager.py
  rotkehlchen/tests/api/test_blockchain.py
  rotkehlchen/utils/interfaces.py
Labels: ready for final review

#4763 Generic CSV Import Docs
  docs/files/rotki_generic_events.csv
  docs/files/rotki_generic_trades.csv
  docs/usage_guide.rst
Labels: ready for peer review
