Repository rotki/rotki, pull requests merged in 2023-10, with the labels that each got.

#6673 paginated addressbook
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/addressbook.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/filtering.py
  rotkehlchen/tests/api/test_addressbook.py
  rotkehlchen/tests/api/test_history_events_export.py
  rotkehlchen/tests/unit/globaldb/test_globaldb_cache.py
  rotkehlchen/tests/unit/test_data_updates.py
Labels: ready for final review

#6679 Abstract code for reloadable decoders
  rotkehlchen/chain/ethereum/modules/curve/curve_cache.py
  rotkehlchen/chain/ethereum/modules/curve/decoder.py
  rotkehlchen/chain/evm/decoding/interfaces.py
  rotkehlchen/chain/optimism/modules/velodrome/decoder.py
  rotkehlchen/tests/unit/test_inquirer.py
Labels: ready for final review

#6712 Add Decoder for The Graph staking
  frontend/app/public/assets/images/protocols/thegraph.svg
  rotkehlchen/chain/ethereum/modules/thegraph/__init__.py
  rotkehlchen/chain/ethereum/modules/thegraph/constants.py
  rotkehlchen/chain/ethereum/modules/thegraph/decoder.py
  rotkehlchen/tests/unit/decoders/test_main.py
  rotkehlchen/tests/unit/decoders/test_thegraph.py
Labels: ready for peer review

#6718 feat(Frontend): refactor layout for custom assets
  frontend/app/src/components/asset-manager/custom/CustomAssetContent.vue
  frontend/app/src/components/asset-manager/custom/CustomAssetSubtitleHint.vue
  frontend/app/src/components/asset-manager/custom/CustomAssetTable.vue
  frontend/app/src/components/helper/CopyButton.vue
  frontend/app/src/components/helper/RowActions.vue
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/src/plugins/rui/index.ts
  frontend/app/tests/e2e/pages/account-balances-page/blockchain-balances-page.ts
  frontend/app/tests/e2e/pages/account-balances-page/manual-balances-page.ts
Labels: ready for peer review

#6723 fix: rename defi yearn mapping for consistency
  rotkehlchen/chain/ethereum/defi/protocols.py
Labels: backend

#6724 Use hashed key instead of string for accounting rules
  rotkehlchen/accounting/rules.py
  rotkehlchen/accounting/structures/base.py
  rotkehlchen/accounting/structures/evm_event.py
  rotkehlchen/chain/ethereum/modules/aave/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/aave/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/balancer/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/balancer/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/compound/accountant.py
  rotkehlchen/chain/ethereum/modules/cowswap/accountant.py
  rotkehlchen/chain/ethereum/modules/curve/accountant.py
  rotkehlchen/chain/ethereum/modules/dxdaomesa/accountant.py
  rotkehlchen/chain/ethereum/modules/eth2/accountant.py
  rotkehlchen/chain/ethereum/modules/gitcoin/accountant.py
  rotkehlchen/chain/ethereum/modules/hop/accountant.py
  rotkehlchen/chain/ethereum/modules/kyber/accountant.py
  rotkehlchen/chain/ethereum/modules/liquity/accountant.py
  rotkehlchen/chain/ethereum/modules/makerdao/accountant.py
  rotkehlchen/chain/ethereum/modules/makerdao/sai/accountant.py
  rotkehlchen/chain/ethereum/modules/oneinch/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/oneinch/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/oneinch/v4/accountant.py
  rotkehlchen/chain/ethereum/modules/pickle_finance/accountant.py
  rotkehlchen/chain/ethereum/modules/sushiswap/accountant.py
  rotkehlchen/chain/ethereum/modules/uniswap/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/uniswap/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/uniswap/v3/accountant.py
  rotkehlchen/chain/ethereum/modules/votium/accountant.py
  rotkehlchen/chain/ethereum/modules/weth/accountant.py
  rotkehlchen/chain/ethereum/modules/yearn/accountant.py
  rotkehlchen/chain/ethereum/modules/zksync/accountant.py
  rotkehlchen/chain/evm/accounting/aggregator.py
  rotkehlchen/chain/evm/accounting/airdrop.py
  rotkehlchen/chain/evm/accounting/interfaces.py
  rotkehlchen/chain/optimism/modules/hop/accountant.py
  rotkehlchen/chain/optimism/modules/velodrome/accountant.py
Labels: ready for final review

#6692 improving binance import
  rotkehlchen/data_import/importers/binance.py
  rotkehlchen/data_import/utils.py
  rotkehlchen/tests/data/binance_history.csv
  rotkehlchen/tests/utils/dataimport.py
Labels: ready for final review

#6727 Move airdrop ledger actions accounting rule to database
  rotkehlchen/accounting/rules.py
  rotkehlchen/chain/evm/accounting/airdrop.py
  rotkehlchen/db/upgrades/v39_v40.py
  rotkehlchen/tests/data/v39_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
Labels: ready for peer review

#6720 add accounting for The Graph staking
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/thegraph/accountant.py
  rotkehlchen/tests/unit/accounting/evm/test_thegraph.py
Labels: ready for final review

#6731 Refactor detected tokens layout
  frontend/app/package.json
  frontend/app/src/components/HintMenuIcon.vue
  frontend/app/src/components/accounts/manual-balances/ManualBalanceTable.vue
  frontend/app/src/components/asset-manager/NewlyDetectedAssetTable.vue
  frontend/app/src/components/asset-manager/custom/CustomAssetTable.vue
  frontend/app/src/components/asset-manager/newly-detected/NewlyDetectedAssetContent.vue
  frontend/app/src/components/asset-manager/newly-detected/NewlyDetectedAssetTable.vue
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/pages/asset-manager/newly-detected/index.vue
  frontend/app/src/plugins/rui/index.ts
  frontend/pnpm-lock.yaml
Labels: ready for peer review

#6737 feat: add gnosis chain support
  frontend/app/src/auto-imports.d.ts
  frontend/app/src/components/accounts/AccountBalances.vue
  frontend/app/src/composables/balances/account-details.ts
  frontend/app/src/composables/balances/refresh.ts
  frontend/app/src/composables/balances/token-detection.ts
  frontend/app/src/composables/blockchain/account-balances/chain.ts
  frontend/app/src/composables/blockchain/account-balances/index.ts
  frontend/app/src/data/defaults.ts
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/src/pages/balances/blockchain/index.vue
  frontend/app/src/pages/settings/api-keys/external/index.vue
  frontend/app/src/store/blockchain/accounts/chains.ts
  frontend/app/src/store/blockchain/balances/chains.ts
  frontend/app/src/store/blockchain/tokens.ts
  frontend/app/src/types/asset/asset-urls.ts
  frontend/app/src/types/blockchain/balances.ts
  frontend/app/src/types/blockchain/chains.ts
  frontend/app/src/types/blockchain/index.ts
  frontend/app/src/types/frontend-settings.ts
  frontend/app/src/types/status.ts
  frontend/app/src/types/user.ts
  frontend/app/src/utils/url.ts
  frontend/app/tests/unit/fixtures/supported-chains.json
  frontend/common/src/blockchain/index.ts
Labels: ready for peer review

#6758 Make event_identifier required only for editing deposit events
  docs/api.rst
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/serialization/deserialize.py
  rotkehlchen/tests/api/test_history_base_entry.py
  rotkehlchen/tests/utils/history_base_entry.py
Labels: ready for final review

#6738 Fetch remotly accounting rules
  docs/api.rst
  rotkehlchen/accounting/rules.py
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/api/websockets/typedefs.py
  rotkehlchen/chain/evm/accounting/structures.py
  rotkehlchen/db/accounting_rules.py
  rotkehlchen/db/constants.py
  rotkehlchen/db/minimized_schema.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/updates.py
  rotkehlchen/db/upgrades/v39_v40.py
  rotkehlchen/tests/api/test_accounting_rules.py
  rotkehlchen/tests/data_migrations/test_migrations.py
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_accounting_rules.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/unit/test_data_updates.py
Labels: ready for final review

#6764 feat(frontend): migrate dashboard component layouts, move snapshot menu button
  frontend/app/src/components/dashboard/NetWorthChart.vue
  frontend/app/src/components/dashboard/OverallBalances.vue
  frontend/app/src/components/dashboard/SnapshotActionButton.vue
  frontend/app/src/components/dashboard/summary-card/SummaryCard.vue
  frontend/app/src/components/dashboard/summary-card/SummaryCardCreateButton.vue
  frontend/app/src/components/dashboard/summary-card/SummaryCardRefreshMenu.vue
  frontend/app/src/components/helper/MenuTooltipButton.vue
  frontend/app/src/components/helper/TimeframeSelector.vue
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/src/pages/dashboard/index.vue
  frontend/app/src/plugins/rui/index.ts
Labels: ready for final review

#6761 gnosis xdai bridge
  frontend/app/public/assets/images/protocols/xdai_bridge.svg
  rotkehlchen/chain/ethereum/decoding/constants.py
  rotkehlchen/chain/ethereum/decoding/decoder.py
  rotkehlchen/chain/ethereum/modules/arbitrum_one_bridge/decoder.py
  rotkehlchen/chain/ethereum/modules/base_bridge/decoder.py
  rotkehlchen/chain/ethereum/modules/optimism_bridge/decoder.py
  rotkehlchen/chain/ethereum/modules/xdai_bridge/__init__.py
  rotkehlchen/chain/ethereum/modules/xdai_bridge/decoder.py
  rotkehlchen/chain/ethereum/utils.py
  rotkehlchen/chain/evm/decoding/utils.py
  rotkehlchen/chain/evm/decoding/xdai_bridge/__init__.py
  rotkehlchen/chain/evm/decoding/xdai_bridge/decoder.py
  rotkehlchen/chain/gnosis/modules/xdai_bridge/__init__.py
  rotkehlchen/chain/gnosis/modules/xdai_bridge/decoder.py
  rotkehlchen/chain/optimism/modules/optimism_bridge/decoder.py
  rotkehlchen/tests/unit/decoders/test_main.py
  rotkehlchen/tests/unit/decoders/test_xdai_bridge.py
Labels: ready for final review

#6777 Remove method field
  rotkehlchen/accounting/constants.py
  rotkehlchen/accounting/cost_basis/base.py
  rotkehlchen/accounting/history_base_entries.py
  rotkehlchen/accounting/pot.py
  rotkehlchen/accounting/rules.py
  rotkehlchen/accounting/structures/base.py
  rotkehlchen/accounting/structures/eth2.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/chain/ethereum/modules/aave/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/aave/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/balancer/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/balancer/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/compound/accountant.py
  rotkehlchen/chain/ethereum/modules/cowswap/accountant.py
  rotkehlchen/chain/ethereum/modules/curve/accountant.py
  rotkehlchen/chain/ethereum/modules/dxdaomesa/accountant.py
  rotkehlchen/chain/ethereum/modules/eth2/accountant.py
  rotkehlchen/chain/ethereum/modules/eth2/structures.py
  rotkehlchen/chain/ethereum/modules/gitcoin/accountant.py
  rotkehlchen/chain/ethereum/modules/hop/accountant.py
  rotkehlchen/chain/ethereum/modules/kyber/accountant.py
  rotkehlchen/chain/ethereum/modules/liquity/accountant.py
  rotkehlchen/chain/ethereum/modules/makerdao/accountant.py
  rotkehlchen/chain/ethereum/modules/makerdao/sai/accountant.py
  rotkehlchen/chain/ethereum/modules/oneinch/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/oneinch/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/oneinch/v4/accountant.py
  rotkehlchen/chain/ethereum/modules/pickle_finance/accountant.py
  rotkehlchen/chain/ethereum/modules/sushiswap/accountant.py
  rotkehlchen/chain/ethereum/modules/thegraph/accountant.py
  rotkehlchen/chain/ethereum/modules/uniswap/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/uniswap/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/uniswap/v3/accountant.py
  rotkehlchen/chain/ethereum/modules/votium/accountant.py
  rotkehlchen/chain/ethereum/modules/weth/accountant.py
  rotkehlchen/chain/ethereum/modules/yearn/accountant.py
  rotkehlchen/chain/ethereum/modules/zksync/accountant.py
  rotkehlchen/chain/evm/accounting/airdrop.py
  rotkehlchen/chain/evm/accounting/interfaces.py
  rotkehlchen/chain/evm/accounting/structures.py
  rotkehlchen/chain/optimism/modules/hop/accountant.py
  rotkehlchen/chain/optimism/modules/velodrome/accountant.py
  rotkehlchen/db/updates.py
  rotkehlchen/exchanges/data_structures.py
  rotkehlchen/tests/db/test_db_accounting_rules.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/unit/accounting/test_exchanges.py
  rotkehlchen/tests/unit/test_cost_basis.py
Labels: ready for final review

#6806 refactor(frontend): migrate staking layout
  frontend/app/src/components/dashboard/OverallBalances.vue
  frontend/app/src/components/dashboard/summary-card/SummaryCard.vue
  frontend/app/src/components/defi/ActiveModules.vue
  frontend/app/src/components/display/AmountCurrency.vue
  frontend/app/src/components/display/amount/AmountDisplay.vue
  frontend/app/src/components/display/amount/CopyTooltip.vue
  frontend/app/src/components/helper/BlockchainAccountSelector.vue
  frontend/app/src/components/helper/hint/ValueAccuracyHint.vue
  frontend/app/src/components/staking/eth/EthStakingPage.vue
  frontend/app/src/components/staking/eth/EthValidatorFilter.vue
  frontend/app/src/components/staking/kraken/KrakenPage.vue
  frontend/app/src/components/staking/kraken/KrakenStaking.vue
  frontend/app/src/components/staking/kraken/KrakenStakingOverview.vue
  frontend/app/src/components/staking/kraken/KrakenStakingReceived.vue
  frontend/app/src/components/staking/liquity/LiquityPools.vue
  frontend/app/src/components/staking/liquity/LiquityStake.vue
  frontend/app/src/components/staking/liquity/LiquityStakingDetails.vue
  frontend/app/src/components/staking/liquity/LiquityStatistics.vue
  frontend/app/src/pages/staking/index.vue
  frontend/app/src/plugins/rui/index.ts
  frontend/app/tests/unit/setup-files/setup.ts
  frontend/app/tests/unit/specs/components/display/amount-display.spec.ts
  frontend/app/tests/unit/specs/stubs/RuiTooltip.ts
Labels: ready for final review

#6807 Fix: unify table layout base
  frontend/app/src/components/helper/TimeframeSelector.vue
  frontend/app/src/components/history/events/HistoryEventsView.vue
  frontend/app/src/components/layout/TablePageLayout.vue
  frontend/app/src/components/staking/eth/EthStakingPage.vue
  frontend/app/src/components/staking/kraken/KrakenPage.vue
  frontend/app/src/components/staking/liquity/LiquityStakingDetails.vue
  frontend/app/src/pages/asset-manager/index.vue
  frontend/app/src/pages/balances/index.vue
  frontend/app/src/pages/dashboard/index.vue
  frontend/app/src/pages/defi/deposits/liquidity/index.vue
  frontend/app/src/pages/defi/index.vue
  frontend/app/src/pages/history/index.vue
  frontend/app/src/pages/import/index.vue
  frontend/app/src/pages/price-manager/index.vue
  frontend/app/src/pages/settings/api-keys/index.vue
  frontend/app/src/pages/staking/index.vue
Labels: ready for final review

#6826 Add information endpoint for accounting linkable settings
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/server.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/db/accounting_rules.py
  rotkehlchen/tests/api/test_accounting_rules.py
Labels: ready for final review
