Repository rotki/rotki, pull requests merged in 2023-11, with the labels that each got.

#6855 Feat(LoginForm): update login user input
  frontend/app/src/components/account-management/login/LoginForm.vue
  frontend/app/src/components/asset-manager/managed/ManagedAssetContent.vue
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/src/pages/user/login/index.vue
  frontend/app/tests/e2e/pages/rotki-app.ts
Labels: ready for peer review

#6865 add filter for customized events
  docs/api.rst
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/filtering.py
  rotkehlchen/tests/db/test_history_events.py
Labels: ready for final review

#6862 specify events without accounting rules
  docs/api.rst
  rotkehlchen/accounting/structures/base.py
  rotkehlchen/accounting/structures/evm_event.py
  rotkehlchen/api/rest.py
  rotkehlchen/db/accounting_rules.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
  rotkehlchen/tests/api/test_history_base_entry.py
Labels: PR review work

#6886 Format as valid json validation error for async validation
  rotkehlchen/api/v1/resources.py
Labels: ready for final review

#6901 Allow to call async the assets import
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/serialization/schemas.py
  rotkehlchen/tests/api/test_user_assets.py
Labels: ready for final review

#6896 Allow to solve multiple rules conflicts at once
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/unresolved_conflicts.py
  rotkehlchen/tests/api/test_accounting_rules.py
Labels: ready for final review

#6905 Feat(frontend): add missing rules actions
  frontend/app/.eslintrc-auto-import.json
  frontend/app/src/auto-imports.d.ts
  frontend/app/src/components/dialogs/MissingRulesDialog.vue
  frontend/app/src/components/history/events/HistoryEventsList.vue
  frontend/app/src/components/history/events/HistoryEventsView.vue
  frontend/app/src/components/history/events/query-status/QueryStatusBar.vue
  frontend/app/src/components/settings/accounting/rule/AccountingRuleForm.vue
  frontend/app/src/components/settings/accounting/rule/AccountingRuleFormDialog.vue
  frontend/app/src/components/settings/accounting/rule/AccountingRuleSetting.vue
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/src/types/history/events/index.ts
  frontend/app/src/utils/settings.ts
Labels: ready for final review

#6908 Use list for conflicts and translate NONE to None
  docs/api.rst
  rotkehlchen/db/unresolved_conflicts.py
  rotkehlchen/tests/api/test_accounting_rules.py
Labels: ready for final review

#6918 Small fixes backend
  rotkehlchen/db/updates.py
  rotkehlchen/inquirer.py
  rotkehlchen/tests/unit/test_inquirer.py
Labels: ready for final review

#6948 Allow the globaldb reset endpoint to be called async
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/tests/api/test_assets_updates.py
Labels: ready for final review

#6953 Accounting rule detection for spend events
  rotkehlchen/accounting/accountant.py
  rotkehlchen/accounting/pot.py
  rotkehlchen/accounting/rules.py
  rotkehlchen/api/rest.py
  rotkehlchen/chain/ethereum/modules/aave/v2/accountant.py
  rotkehlchen/chain/ethereum/modules/balancer/v1/accountant.py
  rotkehlchen/chain/ethereum/modules/curve/accountant.py
  rotkehlchen/chain/ethereum/modules/makerdao/accountant.py
  rotkehlchen/chain/ethereum/modules/thegraph/accountant.py
  rotkehlchen/chain/evm/accounting/aggregator.py
  rotkehlchen/chain/evm/accounting/interfaces.py
  rotkehlchen/chain/evm/accounting/structures.py
  rotkehlchen/chain/optimism/modules/velodrome/accountant.py
  rotkehlchen/db/accounting_rules.py
  rotkehlchen/tests/api/test_history_base_entry.py
  rotkehlchen/tests/db/test_db_accounting_rules.py
  rotkehlchen/tests/fixtures/accounting.py
Labels: ready for final review

#6969 Add endpoint to return count of transactions missing decoding
  docs/api.rst
  docs/websockets.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/websockets/typedefs.py
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/chain/evm/node_inquirer.py
  rotkehlchen/db/evmtx.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
Labels: ready for peer review

#6975 Remove address from the filter for undecoded transactions
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/api/v1/types.py
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/db/evmtx.py
  rotkehlchen/db/filtering.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
  rotkehlchen/tests/unit/test_evm_tx_decoding.py
Labels: ready for final review

#7001 Invalidate cache for accounting rules
  docs/changelog.rst
  rotkehlchen/accounting/accountant.py
  rotkehlchen/api/rest.py
  rotkehlchen/db/accounting_rules.py
  rotkehlchen/tests/api/test_accounting_rules.py
  rotkehlchen/tests/db/test_db_accounting_rules.py
  rotkehlchen/tests/utils/history_base_entry.py
  rotkehlchen/utils/data_structures.py
Labels: ready for final review

#7016 Fix: option to skip chain detection
  frontend/app/src/components/assets/AssetLocations.vue
  frontend/app/src/components/common/PaginatedCards.vue
  frontend/app/src/components/settings/controls/SettingsOption.vue
  frontend/app/src/components/settings/general/EvmChainsToIgnoreSettings.vue
  frontend/app/src/composables/info/chains.ts
  frontend/app/src/data/factories.ts
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/src/pages/settings/general/index.vue
  frontend/app/src/store/settings/general.ts
  frontend/app/src/types/user.ts
Labels: ready for final review
