Repository rotki/rotki, pull requests merged in 2023-05, with the labels that each got.

#5961 NFTs with customized queried addresses
  docs/changelog.rst
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/tests/api/test_nfts.py
Labels: ready for final review

#5954 Decode multiple ETH2 deposits
  rotkehlchen/chain/ethereum/modules/eth2/decoder.py
  rotkehlchen/tests/unit/decoders/test_eth2.py
Labels: ready for final review

#5979 Curve aave withdrawals
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/curve/decoder.py
  rotkehlchen/tests/unit/decoders/test_curve.py
Labels: ready for final review

#5985 Event deletion fix
  rotkehlchen/db/history_events.py
  rotkehlchen/tests/db/test_history_events.py
Labels: ready for peer review

#5980 Curve zap logic tweak
  rotkehlchen/chain/ethereum/modules/curve/decoder.py
  rotkehlchen/tests/unit/decoders/test_curve.py
Labels: ready for final review

#6000 Cleanup identifiers usage in /assets/all
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/tests/api/test_assets.py
Labels: ready for final review

#6013 Early exit in enrichers loop
  rotkehlchen/chain/ethereum/decoding/decoder.py
  rotkehlchen/chain/ethereum/modules/balancer/v1/decoder.py
  rotkehlchen/chain/ethereum/modules/balancer/v2/decoder.py
  rotkehlchen/chain/ethereum/modules/convex/decoder.py
  rotkehlchen/chain/ethereum/modules/curve/decoder.py
  rotkehlchen/chain/ethereum/modules/gitcoin/decoder.py
  rotkehlchen/chain/ethereum/modules/makerdao/sai/decoder.py
  rotkehlchen/chain/ethereum/modules/pickle_finance/decoder.py
  rotkehlchen/chain/ethereum/modules/uniswap/v2/common.py
  rotkehlchen/chain/ethereum/modules/uniswap/v3/decoder.py
  rotkehlchen/chain/ethereum/modules/yearn/decoder.py
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/chain/evm/decoding/structures.py
  rotkehlchen/chain/optimism/decoding/decoder.py
Labels: ready for final review

#5990 Autorefresh balances
  docs/websockets.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/websockets/notifier.py
  rotkehlchen/api/websockets/typedefs.py
  rotkehlchen/chain/ethereum/decoding/decoder.py
  rotkehlchen/chain/ethereum/modules/convex/decoder.py
  rotkehlchen/chain/ethereum/modules/curve/decoder.py
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/chain/evm/decoding/structures.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
  rotkehlchen/tests/fixtures/messages.py
  rotkehlchen/tests/fixtures/websockets.py
  rotkehlchen/tests/unit/decoders/test_aave.py
  rotkehlchen/tests/unit/decoders/test_balancer.py
  rotkehlchen/tests/unit/decoders/test_convex.py
  rotkehlchen/tests/unit/decoders/test_curve.py
  rotkehlchen/tests/unit/decoders/test_enriched.py
  rotkehlchen/tests/unit/decoders/test_ens.py
  rotkehlchen/tests/unit/decoders/test_kyber.py
  rotkehlchen/tests/unit/decoders/test_liquity.py
  rotkehlchen/tests/unit/decoders/test_main.py
  rotkehlchen/tests/unit/decoders/test_makerdao_sai.py
  rotkehlchen/tests/unit/decoders/test_pickle.py
  rotkehlchen/tests/unit/decoders/test_sushiswap.py
  rotkehlchen/tests/unit/decoders/test_uniswapv2.py
  rotkehlchen/tests/unit/decoders/test_uniswapv3.py
  rotkehlchen/tests/unit/decoders/test_votium.py
  rotkehlchen/tests/unit/decoders/test_yearn.py
  rotkehlchen/tests/unit/test_evm_tx_decoding.py
Labels: ready for final review

#6015 Avoid sending ws messages from kraken always when querying events
  rotkehlchen/exchanges/kraken.py
Labels: ready for final review

#6030 Icons mapping for accounting events
  docs/api.rst
  rotkehlchen/accounting/constants.py
  rotkehlchen/api/rest.py
  rotkehlchen/serialization/serialize.py
  rotkehlchen/tests/api/test_misc.py
Labels: ready for final review

#6028 Improve icons query
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/assets/resolver.py
  rotkehlchen/icons.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/data_migrations/test_migrations.py
  rotkehlchen/tests/external_apis/test_coingecko.py
  rotkehlchen/utils/data_structures.py
Labels: ready for final review

#6042 Curve zaps with no event
  rotkehlchen/chain/ethereum/modules/curve/decoder.py
  rotkehlchen/tests/unit/decoders/test_curve.py
Labels: ready for final review

#6066 Make sure that usd value is populated before returning liquity statistics
  rotkehlchen/api/rest.py
  rotkehlchen/chain/ethereum/modules/liquity/statistics.py
  rotkehlchen/db/history_events.py
  rotkehlchen/history/events.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tests/api/test_liquity.py
  rotkehlchen/tests/data/liquity_stats.db
Labels: ready for peer review

#6059 filtering field with exclude and include behaviour was added
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/fields.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/api/v1/types.py
  rotkehlchen/db/filtering.py
  rotkehlchen/exchanges/kraken.py
  rotkehlchen/tests/api/test_eth2.py
  rotkehlchen/tests/db/test_history_events.py
Labels: ready for final review

#6083 Include explanation about liquity
  docs/images/liquity_stats.png
  docs/usage_guide.rst
Labels: documentation

#6087 transform beaconchain name to eth staking on str method
  rotkehlchen/types.py
Labels: ready for final review

#6082 Hacky import of custom assets
  rotkehlchen/globaldb/assets_management.py
  rotkehlchen/serialization/schemas.py
  rotkehlchen/tests/data/exported_assets.json
  rotkehlchen/tests/data/exported_assets.zip
Labels: ready for final review

#6107 Update ens avatars and history events sections
  docs/images/edit_eth_event.png
  docs/images/edit_evm_event.png
  docs/images/ens_resolution.png
  docs/images/eth_tx_query_process.png
  docs/images/events_query_process.png
  docs/images/redecode_events.png
  docs/usage_guide.rst
Labels: ready for final review

#6121 Add decoder for compunding CRV in convex
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/convex/decoder.py
  rotkehlchen/tests/unit/decoders/test_convex.py
Labels: ready for peer review

#6131 User approval to resume from user db backup
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/data_handler.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/api/test_users.py
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/db/test_defi_events.py
  rotkehlchen/tests/db/test_evmtx.py
  rotkehlchen/tests/external_apis/test_etherscan.py
  rotkehlchen/tests/fixtures/db.py
  rotkehlchen/tests/fixtures/rotkehlchen.py
  rotkehlchen/tests/integration/test_premium.py
  rotkehlchen/tests/test_users.py
  rotkehlchen/tests/unit/test_app.py
  rotkehlchen/tests/utils/xpubs.py
  tools/assets_database/main.py
  tools/uniswapv2/detect.py
Labels: ready for final review

#6138 Add aave v2 liquidations
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/aave/v1/decoder.py
  rotkehlchen/chain/ethereum/modules/aave/v2/decoder.py
  rotkehlchen/tests/unit/decoders/test_aave.py
Labels: ready for final review

#6161 Rename polygon for api
  rotkehlchen/types.py
Labels: ready for final review

#6157 Bitcoin tax import support
  docs/api.rst
  rotkehlchen/assets/converters.py
  rotkehlchen/data_import/importers/bitcoin_tax.py
  rotkehlchen/data_import/manager.py
  rotkehlchen/tests/api/test_data_import.py
  rotkehlchen/tests/data/bitcoin_tax_spending.csv
  rotkehlchen/tests/data/bitcoin_tax_trades.csv
  rotkehlchen/tests/utils/dataimport.py
Labels: ready for final review

#6171 Fix curve zerion double counting
  docs/changelog.rst
  rotkehlchen/chain/aggregator.py
Labels: ready for final review

#6168 Temporary fix for history events accounting
  docs/changelog.rst
  rotkehlchen/accounting/structures/base.py
  rotkehlchen/accounting/transactions.py
  rotkehlchen/tests/unit/accounting/test_default_settings.py
Labels: ready for final review

#6160 feat: filter events by contract address and product
  frontend/app/src/components/history/events/HistoryEventForm.vue
  frontend/app/src/composables/api/history/events.ts
  frontend/app/src/composables/filters/events.ts
  frontend/app/src/composables/history/events/mapping.ts
  frontend/app/src/locales/en.json
  frontend/app/src/types/history/events/event-type.ts
  frontend/app/src/types/history/events/index.ts
Labels: frontend

#6174 fix: some small things on history events
  frontend/app/src/components/history/events/HistoryEventForm.vue
  frontend/app/src/components/history/events/HistoryEventsView.vue
  frontend/app/src/components/inputs/ComboboxWithCustomInput.vue
  frontend/app/src/components/table-filter/TableFilter.vue
  frontend/app/src/locales/en.json
  frontend/app/src/store/prices/historic.ts
Labels: frontend
