Repository rotki/rotki, pull requests merged in 2023-06, with the labels that each got.

#6176 feat: update date time picker
  frontend/app/package.json
  frontend/app/src/components/dialogs/DateTimePicker.vue
  frontend/app/src/components/history/trades/ExternalTradeForm.vue
  frontend/app/src/components/inputs/AmountInput.vue
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/vite.config.ts
  frontend/pnpm-lock.yaml
Labels: frontend

#6196 Provide the correct evm chain id when detecting evm addresses
  rotkehlchen/chain/aggregator.py
  rotkehlchen/tests/api/blockchain/test_evm.py
Labels: ready for final review

#6199 fix(frontend): account label removal issue
  frontend/app/src/store/blockchain/accounts/addresses-names.ts
  frontend/app/tests/unit/specs/store/blockchain/accounts/addresses-names.spec.ts
Labels: frontend

#6211 Fixes balance calculation and wrong asset icon
  frontend/app/src/components/display/BalanceDisplay.vue
  frontend/app/src/components/helper/display/icons/AssetIcon.vue
  frontend/app/src/types/currencies.ts
Labels: frontend

#6210 feat: update get premium nudge mechanism
  frontend/app/src/components/account-management/PremiumReminder.vue
  frontend/app/src/components/app/AppIndicators.vue
  frontend/app/src/components/premium/GetPremiumButton.vue
  frontend/app/src/composables/premium.ts
  frontend/app/src/composables/user/account.ts
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/src/pages/settings/api-keys/premium/index.vue
  frontend/app/src/pages/user/login/index.vue
  frontend/app/src/store/session/auth.ts
  frontend/app/src/store/session/index.ts
  frontend/app/tests/e2e/pages/rotki-app.ts
  frontend/app/tests/e2e/specs/app/account-creation.spec.ts
  frontend/app/tests/e2e/specs/app/settings/accounting.spec.ts
  frontend/app/tests/e2e/specs/app/settings/general.spec.ts
  frontend/app/tests/e2e/specs/app/settings/user-security.spec.ts
  frontend/app/tests/unit/specs/components/premium/get-premium-button.spec.ts
  frontend/app/tests/unit/specs/composables/user/account.spec.ts
Labels: frontend

#6191 correctly pick the explorer url for the different evm events
  docs/changelog.rst
  rotkehlchen/accounting/export/csv.py
  rotkehlchen/accounting/structures/processed_event.py
  rotkehlchen/api/rest.py
  rotkehlchen/tests/unit/accounting/test_basic.py
Labels: ready for final review

#6182 refactor(frontend): adjust form validation for several forms
  frontend/app/.eslintrc-auto-import.json
  frontend/app/src/auto-imports.d.ts
  frontend/app/src/components/accounts/manual-balances/ManualBalancesForm.vue
  frontend/app/src/components/asset-manager/CustomAssetContent.vue
  frontend/app/src/components/asset-manager/CustomAssetForm.vue
  frontend/app/src/components/asset-manager/CustomAssetFormDialog.vue
  frontend/app/src/components/history/events/HistoryEventForm.vue
  frontend/app/src/components/history/events/HistoryEventFormDialog.vue
  frontend/app/src/components/history/events/HistoryEventsView.vue
  frontend/app/src/components/history/events/HistoryFormDialog.vue
  frontend/app/src/components/history/events/tx/TransactionForm.vue
  frontend/app/src/components/history/events/tx/TransactionFormDialog.vue
  frontend/app/src/components/history/ledger-actions/LedgerActionContent.vue
  frontend/app/src/components/history/ledger-actions/LedgerActionForm.vue
  frontend/app/src/components/history/ledger-actions/LedgerActionFormDialog.vue
  frontend/app/src/components/history/trades/ExternalTradeForm.vue
  frontend/app/src/components/history/trades/ExternalTradeFormDialog.vue
  frontend/app/src/components/notes/UserNotesForm.vue
  frontend/app/src/components/notes/UserNotesFormDialog.vue
  frontend/app/src/components/notes/UserNotesList.vue
  frontend/app/src/components/profitloss/ProfitLossEventType.vue
  frontend/app/src/components/profitloss/ReportMissingAcquisitions.vue
  frontend/app/src/components/settings/data-security/data-management/PurgeData.vue
  frontend/app/src/composables/history/events/form.ts
  frontend/app/src/composables/history/events/tx/form.ts
  frontend/app/src/composables/history/events/tx/index.ts
  frontend/app/src/composables/history/ledger-actions/form.ts
  frontend/app/src/composables/notes/form.ts
  frontend/app/src/pages/balances/manual/index.vue
Labels: frontend

#6209 refactor(frontend): adjust form validation for asset and price manager
  frontend/app/.eslintrc-auto-import.json
  frontend/app/src/auto-imports.d.ts
  frontend/app/src/components/asset-manager/custom/CustomAssetContent.vue
  frontend/app/src/components/asset-manager/custom/CustomAssetForm.vue
  frontend/app/src/components/asset-manager/custom/CustomAssetFormDialog.vue
  frontend/app/src/components/asset-manager/custom/CustomAssetTable.vue
  frontend/app/src/components/asset-manager/managed/ManagedAssetContent.vue
  frontend/app/src/components/asset-manager/managed/ManagedAssetForm.vue
  frontend/app/src/components/asset-manager/managed/ManagedAssetFormDialog.vue
  frontend/app/src/components/asset-manager/managed/ManagedAssetTable.vue
  frontend/app/src/components/dialogs/BigDialog.vue
  frontend/app/src/components/price-manager/historic/HistoricPriceForm.vue
  frontend/app/src/components/price-manager/latest/LatestPriceForm.vue
  frontend/app/src/components/price-manager/latest/LatestPriceTable.vue
  frontend/app/src/composables/assets/forms/managed-asset-form.ts
  frontend/app/src/composables/price-manager/historic/form.ts
  frontend/app/src/composables/price-manager/latest/form.ts
  frontend/app/src/pages/price-manager/historic/index.vue
  frontend/app/src/pages/price-manager/latest/index.vue
  frontend/app/tests/e2e/pages/assets-manager-page.ts
Labels: frontend

#6218 Fix error checking status of frontend settings for CSV exporter
  rotkehlchen/accounting/export/csv.py
  rotkehlchen/tests/unit/test_cost_basis.py
Labels: ready for final review

#6185 Compound liquidations
  rotkehlchen/chain/ethereum/modules/compound/decoder.py
  rotkehlchen/tests/unit/decoders/test_compound.py
Labels: ready for final review

#6231 Decode aave suply of ETH correctly
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/aave/v2/decoder.py
  rotkehlchen/tests/unit/decoders/test_aave.py
Labels: ready for final review

#6234 Fix edge case in uniswap liquidity withdrawal
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/uniswap/v2/common.py
  rotkehlchen/tests/unit/decoders/test_uniswapv2.py
Labels: ready for final review

#6261 Fix kyber decoder for trades
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/kyber/decoder.py
  rotkehlchen/tests/unit/decoders/test_kyber.py
Labels: ready for peer review

#6269 Remove aave events after subgraph removal
  rotkehlchen/chain/ethereum/modules/aave/aave.py
  rotkehlchen/chain/ethereum/modules/aave/structures.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/minimized_schema.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/upgrades/v37_v38.py
  rotkehlchen/serialization/serialize.py
  rotkehlchen/tests/data/v37_rotkehlchen.db
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/db/test_defi_events.py
Labels: ready for peer review

#6296 Update spam assets in data migration
  rotkehlchen/data_migrations/migrations/migration_10.py
  rotkehlchen/db/updates.py
Labels: ready for peer review

#6305 Fix error adding multiple evm tokens with the same name and symbol
  docs/changelog.rst
  rotkehlchen/api/rest.py
  rotkehlchen/globaldb/handler.py
  rotkehlchen/tests/unit/globaldb/test_globaldb.py
Labels: ready for peer review

#6316 Decode an 1inchv4 swap via uniswap v3
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/oneinch/constants.py
  rotkehlchen/chain/ethereum/modules/oneinch/v2/decoder.py
  rotkehlchen/chain/ethereum/modules/oneinch/v4/__init__.py
  rotkehlchen/chain/ethereum/modules/oneinch/v4/accountant.py
  rotkehlchen/chain/ethereum/modules/oneinch/v4/constants.py
  rotkehlchen/chain/ethereum/modules/oneinch/v4/decoder.py
  rotkehlchen/chain/evm/decoding/oneinch/decoder.py
  rotkehlchen/chain/polygon_pos/modules/oneinch/decoder.py
  rotkehlchen/tests/unit/decoders/test_1inch.py
  rotkehlchen/tests/unit/decoders/test_main.py
Labels: ready for peer review

#6332 Fix the test for querying makerdao vaults
  rotkehlchen/tests/api/test_makerdao_vaults.py
Labels: ready for peer review

#6353 1inchv4 eth transfers decoding
  rotkehlchen/chain/ethereum/modules/oneinch/v4/decoder.py
  rotkehlchen/tests/unit/decoders/test_1inch.py
Labels: ready for peer review
