Repository rotki/rotki, pull requests merged in 2023-12, with the labels that each got.

#7044 Detect unicode in spam tokens.
  requirements.txt
  rotkehlchen/assets/utils.py
  rotkehlchen/constants/misc.py
  rotkehlchen/db/settings.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tests/unit/globaldb/test_globaldb.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for peer review

#7072 Eth withdrwal events will now respect acc rules
  docs/changelog.rst
  rotkehlchen/accounting/accountant.py
  rotkehlchen/accounting/structures/eth2.py
  rotkehlchen/tests/unit/accounting/test_settings.py
  rotkehlchen/tests/unit/accounting/test_staking.py
  rotkehlchen/tests/unit/test_cost_basis.py
  rotkehlchen/tests/utils/accounting.py
Labels: ready for final review

#7067 Change block-number query failure as warning with user-friendly message
  rotkehlchen/chain/evm/transactions.py
  rotkehlchen/tests/api/test_balances.py
  rotkehlchen/tests/api/test_history.py
Labels: ready for final review, python

#7113 fix (#6979): remove case-sensitivity of generic import trade type
  rotkehlchen/data_import/importers/rotki_trades.py
  rotkehlchen/tests/data/rotki_generic_trades.csv
  rotkehlchen/tests/utils/dataimport.py
  rotkehlchen/types.py
Labels: ready for final review

#7117 fix (metamask): better notes and adjust swap event
  rotkehlchen/chain/evm/decoding/metamask/decoder.py
  rotkehlchen/tests/unit/decoders/test_metamask.py
Labels: ready for final review

#7122 Add augmented detection of spam tokens
  rotkehlchen/assets/asset.py
  rotkehlchen/chain/evm/utils.py
  rotkehlchen/constants/misc.py
  rotkehlchen/constants/timing.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/settings.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tasks/utils.py
  rotkehlchen/tests/api/test_assets_updates.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for peer review

#7125 fix (#7082): add `location_name` in trade query
  docs/api.rst
  docs/changelog.rst
  rotkehlchen/history/events.py
  rotkehlchen/tests/unit/test_trades.py
  rotkehlchen/tests/utils/exchanges.py
Labels: ready for final review

#7134 Handle unknown assets in augmented spam check
  rotkehlchen/tasks/assets.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7136 Fix/#7123: Check for balance of EOA address on ethereum for checking its activity
  docs/changelog.rst
  rotkehlchen/externalapis/etherscan.py
  rotkehlchen/tests/external_apis/test_etherscan.py
  rotkehlchen/tests/unit/test_trades.py
Labels: ready for final review

#7150 Fix (bittrex): add support for old CSVs
  rotkehlchen/data_import/importers/bittrex.py
  rotkehlchen/tests/api/test_data_import.py
  rotkehlchen/tests/data/bittrex_order_history_old.csv
  rotkehlchen/tests/data/bittrex_order_history_older.csv
  rotkehlchen/tests/data/bittrex_tx_history_deposits.csv
  rotkehlchen/tests/data/bittrex_tx_history_deposits_old.csv
  rotkehlchen/tests/data/bittrex_tx_history_withdrawals.csv
  rotkehlchen/tests/data/bittrex_tx_history_withdrawals_old.csv
  rotkehlchen/tests/utils/dataimport.py
Labels: ready for final review

#7159 Feat (userdb): add a new cache table
  rotkehlchen/db/minimized_schema.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/settings.py
  rotkehlchen/db/upgrade_manager.py
  rotkehlchen/db/upgrades/v40_v41.py
  rotkehlchen/db/utils.py
  rotkehlchen/tests/data/v40_rotkehlchen.db
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_upgrades.py
Labels: ready for final review

#7177 Avoid extra queries of prices for assets in collections
  docs/changelog.rst
  rotkehlchen/globaldb/handler.py
  rotkehlchen/inquirer.py
  rotkehlchen/tests/unit/globaldb/test_globaldb.py
  rotkehlchen/tests/unit/test_inquirer.py
Labels: ready for final review

#7081 Add queries for trades and balances bybit
  frontend/app/public/assets/images/protocols/bybit.svg
  frontend/app/src/types/exchanges.ts
  rotkehlchen/assets/converters.py
  rotkehlchen/assets/exchanges_mappings/bybit.py
  rotkehlchen/constants/location_details.py
  rotkehlchen/db/schema.py
  rotkehlchen/exchanges/bybit.py
  rotkehlchen/exchanges/constants.py
  rotkehlchen/exchanges/exchange.py
  rotkehlchen/exchanges/gemini.py
  rotkehlchen/exchanges/utils.py
  rotkehlchen/tests/exchanges/test_bybit.py
  rotkehlchen/tests/fixtures/exchanges/__init__.py
  rotkehlchen/tests/fixtures/exchanges/bybit.py
  rotkehlchen/tests/utils/exchanges.py
  rotkehlchen/types.py
Labels: ready for final review

#7170 Optimizations on inquirer and assets
  rotkehlchen/assets/asset.py
  rotkehlchen/assets/resolver.py
  rotkehlchen/inquirer.py
  rotkehlchen/tests/unit/test_defi_oracles.py
Labels: ready for final review

#7181 Allow to mark spam assets as false positive
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/server.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/globaldb/cache.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tests/api/test_assets.py
  rotkehlchen/types.py
Labels: ready for final review

#7184 Make decimal optional and add LRU cache to inquirer
  rotkehlchen/api/rest.py
  rotkehlchen/assets/asset.py
  rotkehlchen/chain/ethereum/defi/price.py
  rotkehlchen/chain/ethereum/modules/aave/aave.py
  rotkehlchen/chain/ethereum/modules/aave/common.py
  rotkehlchen/chain/ethereum/modules/yearn/vaultsv2.py
  rotkehlchen/chain/ethereum/utils.py
  rotkehlchen/chain/evm/utils.py
  rotkehlchen/globaldb/cache.py
  rotkehlchen/inquirer.py
  rotkehlchen/tests/unit/test_inquirer.py
  rotkehlchen/utils/data_structures.py
Labels: ready for final review

#7183 feat(frontend): allow running task cancellation
  docs/changelog.rst
  frontend/app/.eslintrc-auto-import.json
  frontend/app/src/auto-imports.d.ts
  frontend/app/src/components/import/ImportSource.vue
  frontend/app/src/components/status/NotificationIndicator.vue
  frontend/app/src/components/status/notifications/PendingTask.vue
  frontend/app/src/components/status/notifications/PendingTasks.vue
  frontend/app/src/composables/api/task.ts
  frontend/app/src/composables/assets/index.ts
  frontend/app/src/composables/assets/retrieval.ts
  frontend/app/src/composables/balances/index.ts
  frontend/app/src/composables/blockchain/accounts/index.ts
  frontend/app/src/composables/blockchain/balances/index.ts
  frontend/app/src/composables/blockchain/index.ts
  frontend/app/src/composables/history/asset-movements/index.ts
  frontend/app/src/composables/history/events/tx/decoding.ts
  frontend/app/src/composables/history/events/tx/index.ts
  frontend/app/src/composables/history/trades/index.ts
  frontend/app/src/composables/session/purge.ts
  frontend/app/src/composables/session/sync.ts
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/gr.json
  frontend/app/src/pages/defi/airdrops/index.vue
  frontend/app/src/pages/reports/index.vue
  frontend/app/src/store/balances/exchanges.ts
  frontend/app/src/store/balances/manual.ts
  frontend/app/src/store/balances/non-fungible.ts
  frontend/app/src/store/balances/prices.ts
  frontend/app/src/store/blockchain/accounts/addresses-names.ts
  frontend/app/src/store/blockchain/accounts/btc.ts
  frontend/app/src/store/blockchain/accounts/eth.ts
  frontend/app/src/store/blockchain/balances/eth.ts
  frontend/app/src/store/blockchain/tokens.ts
  frontend/app/src/store/defi/aave/index.ts
  frontend/app/src/store/defi/compound/index.ts
  frontend/app/src/store/defi/index.ts
  frontend/app/src/store/defi/makerdao/index.ts
  frontend/app/src/store/defi/yearn/index.ts
  frontend/app/src/store/prices/historic.ts
  frontend/app/src/store/reports/index.ts
  frontend/app/src/store/staking/eth2.ts
  frontend/app/src/store/tasks/index.ts
  frontend/app/src/types/task.ts
  frontend/app/src/utils/fetch-async.ts
  frontend/app/src/utils/index.ts
Labels: ready for final review

#7189 Add enum to set status of processed events
  docs/api.rst
  rotkehlchen/accounting/accountant.py
  rotkehlchen/accounting/structures/base.py
  rotkehlchen/accounting/structures/evm_event.py
  rotkehlchen/accounting/types.py
  rotkehlchen/api/rest.py
  rotkehlchen/db/accounting_rules.py
  rotkehlchen/tests/api/test_accounting_rules.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
  rotkehlchen/tests/db/test_db_accounting_rules.py
  rotkehlchen/tests/unit/test_history_events.py
  rotkehlchen/tests/utils/factories.py
Labels: ready for final review

#7178 Feat/cache: Move unrelated values from `settings` to `key_value_cache`
  rotkehlchen/api/rest.py
  rotkehlchen/chain/aggregator.py
  rotkehlchen/chain/constants.py
  rotkehlchen/constants/misc.py
  rotkehlchen/data_migrations/manager.py
  rotkehlchen/db/cache.py
  rotkehlchen/db/constants.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/settings.py
  rotkehlchen/db/updates.py
  rotkehlchen/db/upgrades/v40_v41.py
  rotkehlchen/premium/sync.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tasks/utils.py
  rotkehlchen/tests/api/test_periodic.py
  rotkehlchen/tests/api/test_settings.py
  rotkehlchen/tests/data/pnl_debug.json
  rotkehlchen/tests/data_migrations/test_migrations.py
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/integration/test_premium.py
  rotkehlchen/tests/unit/test_data_updates.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7196 Cache timestamp to block queries to etherscan
  rotkehlchen/externalapis/etherscan.py
Labels: ready for final review
