Repository rotki/rotki, pull requests merged in 2024-05, with the labels that each got.

#7869 Fix (_maybe_create_calendar_reminder): Include it (PR of the day)
  rotkehlchen/tasks/manager.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7867 Prevent user errors when checking compound tokens
  rotkehlchen/chain/evm/decoding/compound/v3/balances.py
  rotkehlchen/chain/evm/decoding/compound/v3/decoder.py
Labels: ready for final review

#7862 fix(backend): update counterparty image and icon
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/chain/evm/decoding/polygon/constants.py
  rotkehlchen/chain/evm/decoding/types.py
  rotkehlchen/serialization/serialize.py
  rotkehlchen/tests/api/test_misc.py
Labels: ready for final review

#7841 Add balances query for vested GRT tokens
  rotkehlchen/chain/evm/decoding/thegraph/balances.py
  rotkehlchen/chain/evm/decoding/thegraph/decoder.py
  rotkehlchen/tests/unit/decoders/test_thegraph.py
  rotkehlchen/tests/unit/test_protocol_balances.py
Labels: ready for final review

#7871 Add Kyberswap aggregator decoder
  docs/changelog.rst
  rotkehlchen/chain/arbitrum_one/modules/kyber/__init__.py
  rotkehlchen/chain/arbitrum_one/modules/kyber/decoder.py
  rotkehlchen/chain/base/modules/kyber/__init__.py
  rotkehlchen/chain/base/modules/kyber/decoder.py
  rotkehlchen/chain/ethereum/modules/kyber/constants.py
  rotkehlchen/chain/ethereum/modules/kyber/decoder.py
  rotkehlchen/chain/evm/decoding/kyber/__init__.py
  rotkehlchen/chain/evm/decoding/kyber/constants.py
  rotkehlchen/chain/evm/decoding/kyber/decoder.py
  rotkehlchen/chain/optimism/modules/kyber/__init__.py
  rotkehlchen/chain/optimism/modules/kyber/decoder.py
  rotkehlchen/chain/polygon_pos/modules/kyber/__init__.py
  rotkehlchen/chain/polygon_pos/modules/kyber/decoder.py
  rotkehlchen/chain/scroll/modules/kyber/__init__.py
  rotkehlchen/chain/scroll/modules/kyber/decoder.py
  rotkehlchen/tests/unit/decoders/test_kyber.py
  rotkehlchen/tests/unit/decoders/test_main.py
Labels: ready for final review

#7876 Allow to track airdrops that require remote calls
  docs/installation_guide.rst
  rotkehlchen/chain/ethereum/airdrops.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tests/api/test_metadata.py
  rotkehlchen/tests/unit/test_ethereum_airdrops.py
Labels: ready for final review, release blocker

#7884 Repull internal txs when redecoding transactions
  rotkehlchen/api/rest.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
Labels: ready for final review

#7891 Fix (location_asset_mappings): Already existing
  rotkehlchen/db/updates.py
  rotkehlchen/globaldb/handler.py
  rotkehlchen/tests/unit/test_data_updates.py
Labels: ready for final review

#7880 feat(evm): add spam transaction caching
  rotkehlchen/chain/evm/constants.py
  rotkehlchen/chain/evm/transactions.py
  rotkehlchen/tests/unit/test_chains_aggregator.py
Labels: ready for final review

#7936 Use new thegraph network
  docs/changelog.rst
  rotkehlchen/chain/ethereum/graph.py
  rotkehlchen/chain/ethereum/modules/balancer/balancer.py
  rotkehlchen/chain/ethereum/modules/ens/decoder.py
  rotkehlchen/errors/api.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
  rotkehlchen/tests/fixtures/__init__.py
  rotkehlchen/tests/fixtures/thegraph.py
  rotkehlchen/tests/unit/decoders/test_ens.py
  rotkehlchen/tests/unit/test_graph.py
  rotkehlchen/tests/utils/constants.py
  rotkehlchen/types.py
Labels: ready for final review

#7923 Feat (History Events): Consistent free and premium
  docs/changelog.rst
  frontend/app/src/components/history/events/HistoryEventsView.vue
  frontend/app/src/locales/en.json
  frontend/app/src/locales/fr.json
  rotkehlchen/db/filtering.py
  rotkehlchen/db/history_events.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
  rotkehlchen/tests/db/test_history_events.py
  rotkehlchen/tests/external_apis/test_blockscout.py
Labels: ready for final review

#7918 fix(balances): fix graph balance querying and detection
  docs/changelog.rst
  rotkehlchen/chain/arbitrum_one/modules/thegraph/balances.py
  rotkehlchen/chain/ethereum/constants.py
  rotkehlchen/chain/ethereum/modules/thegraph/balances.py
  rotkehlchen/chain/ethereum/modules/thegraph/constants.py
  rotkehlchen/chain/ethereum/modules/thegraph/decoder.py
  rotkehlchen/chain/ethereum/transactions.py
  rotkehlchen/chain/evm/decoding/thegraph/balances.py
  rotkehlchen/chain/evm/decoding/thegraph/constants.py
  rotkehlchen/chain/evm/decoding/thegraph/decoder.py
  rotkehlchen/db/cache.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tasks/utils.py
  rotkehlchen/tests/unit/decoders/test_thegraph.py
  rotkehlchen/tests/unit/test_protocol_balances.py
Labels: ready for final review

#7953 Avoid marking as spam whitelisted tokens
  docs/changelog.rst
  rotkehlchen/globaldb/cache.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tests/unit/test_assets.py
Labels: ready for final review

#7955 Feat (ZkSync-lite): Notify decoding progress
  docs/changelog.rst
  docs/websockets.rst
  rotkehlchen/api/rest.py
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/chain/zksync_lite/manager.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
Labels: ready for final review

#7971 Reduce the set of punctuation symbols used for spam tokens
  rotkehlchen/assets/utils.py
  rotkehlchen/tests/unit/globaldb/test_globaldb.py
Labels: ready for final review

#7966 feat(hop): Add Hop Protocol LP event decoding
  rotkehlchen/chain/ethereum/modules/hop/decoder.py
  rotkehlchen/chain/evm/decoding/hop/constants.py
  rotkehlchen/chain/evm/decoding/hop/decoder.py
  rotkehlchen/chain/evm/decoding/hop/structures.py
  rotkehlchen/tests/unit/decoders/test_hop.py
Labels: ready for final review

#7963 Chore (CI): Fail if VCR is not full rebased
  .github/workflows/task_backend_tests.yml
Labels: ready for peer review

#7980 Clean code
  rotkehlchen/chain/arbitrum_one/modules/kyber/decoder.py
  rotkehlchen/chain/base/modules/kyber/decoder.py
  rotkehlchen/chain/ethereum/modules/polygon/decoder.py
  rotkehlchen/chain/gnosis/modules/airdrops/__init__.py
  rotkehlchen/chain/gnosis/modules/airdrops/decoder.py
  rotkehlchen/chain/gnosis/modules/sdai/decoder.py
  rotkehlchen/chain/optimism/modules/kyber/decoder.py
  rotkehlchen/chain/polygon_pos/modules/kyber/decoder.py
  rotkehlchen/chain/scroll/modules/kyber/decoder.py
Labels: ready for final review

#7989 Feat (Accounting rules): API for Import/Export
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/server.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/chain/evm/accounting/structures.py
  rotkehlchen/db/accounting_rules.py
  rotkehlchen/tests/api/test_accounting_rules.py
Labels: ready for final review

#7995 Fix (Airdrops): `has_decoder` field
  docs/api.rst
  docs/contribute.rst
  rotkehlchen/chain/ethereum/airdrops.py
  rotkehlchen/tests/unit/test_ethereum_airdrops.py
Labels: ready for final review

#8004 Fix (Airdrops): Always include `has_decoder` field
  docs/api.rst
  rotkehlchen/chain/ethereum/airdrops.py
  rotkehlchen/tests/unit/test_ethereum_airdrops.py
Labels: ready for peer review

#7999 feat(cctp): add decoder for CCTP bridge events
  docs/changelog.rst
  frontend/app/public/assets/images/protocols/cctp.svg
  rotkehlchen/chain/arbitrum_one/modules/cctp/__init__.py
  rotkehlchen/chain/arbitrum_one/modules/cctp/constants.py
  rotkehlchen/chain/arbitrum_one/modules/cctp/decoder.py
  rotkehlchen/chain/base/modules/cctp/__init__.py
  rotkehlchen/chain/base/modules/cctp/constants.py
  rotkehlchen/chain/base/modules/cctp/decoder.py
  rotkehlchen/chain/ethereum/modules/cctp/__init__.py
  rotkehlchen/chain/ethereum/modules/cctp/constants.py
  rotkehlchen/chain/ethereum/modules/cctp/decoder.py
  rotkehlchen/chain/evm/decoding/cctp/__init__.py
  rotkehlchen/chain/evm/decoding/cctp/constants.py
  rotkehlchen/chain/evm/decoding/cctp/decoder.py
  rotkehlchen/chain/optimism/modules/cctp/__init__.py
  rotkehlchen/chain/optimism/modules/cctp/constants.py
  rotkehlchen/chain/optimism/modules/cctp/decoder.py
  rotkehlchen/chain/polygon_pos/modules/cctp/__init__.py
  rotkehlchen/chain/polygon_pos/modules/cctp/constants.py
  rotkehlchen/chain/polygon_pos/modules/cctp/decoder.py
  rotkehlchen/tests/unit/decoders/test_cctp.py
  rotkehlchen/tests/unit/decoders/test_main.py
Labels: ready for final review

#7987 Split macos runners to x86 and apple silicon and update x86 runner to macos-12
  .github/.env.ci
  .github/workflows/rotki_dev_builds.yml
  .github/workflows/rotki_release.yaml
  Dockerfile
  frontend/app/.electron-builder.config.js
  package.py
  packaging/setup-macos-python.sh
  rotkehlchen.spec
Labels: ready for final review

#8011 feat(oneinch): add support for 1inch v6 decoder
  docs/changelog.rst
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/chain/evm/decoding/oneinch/constants.py
  rotkehlchen/chain/evm/decoding/oneinch/v6/__init__.py
  rotkehlchen/chain/evm/decoding/oneinch/v6/decoder.py
  rotkehlchen/tests/unit/decoders/test_1inch.py
  rotkehlchen/tests/unit/decoders/test_main.py
Labels: ready for final review

#8020 Feat (CI): Work with PR cassettes
  .github/workflows/task_backend_tests.yml
Labels: ready for peer review

#8021 Chore (docs): Update cassettes contribution guide
  docs/contribute.rst
Labels: ready for final review
