Repository rotki/rotki, pull requests merged in 2024-01, with the labels that each got.

#7195 Protect against deserialization errors in opensea
  rotkehlchen/chain/ethereum/modules/nft/nfts.py
  rotkehlchen/externalapis/opensea.py
  rotkehlchen/serialization/deserialize.py
  rotkehlchen/tests/api/test_nfts.py
  rotkehlchen/tests/fixtures/blockchain.py
Labels: ready for final review

#7201 Fix (#7178): Follow-up fixes
  rotkehlchen/api/rest.py
  rotkehlchen/db/cache.py
  rotkehlchen/db/settings.py
  rotkehlchen/db/updates.py
  rotkehlchen/db/upgrades/v40_v41.py
  rotkehlchen/tests/api/test_users.py
  rotkehlchen/tests/data_migrations/test_migrations.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/unit/test_data_updates.py
Labels: ready for final review

#7211 Add missing bybit location to db upgrade
  rotkehlchen/db/upgrades/v40_v41.py
Labels: ready for final review

#7210 feat (#7146): Update asset columns in PnL CSV
  docs/changelog.rst
  rotkehlchen/accounting/export/csv.py
  rotkehlchen/accounting/structures/processed_event.py
  rotkehlchen/tests/api/test_pnl_csv.py
  rotkehlchen/tests/utils/history.py
Labels: ready for final review

#7219 Provide more information when adding evm accounts
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/chain/aggregator.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/api/blockchain/test_evm.py
Labels: ready for final review

#7226 Handle correctly USDT in nexo mapping
  docs/changelog.rst
  rotkehlchen/assets/converters.py
  rotkehlchen/assets/exchanges_mappings/nexo.py
  rotkehlchen/tests/unit/test_assets.py
Labels: ready for final review

#7209 feat (cache): move single timestamps to cache
  rotkehlchen/api/rest.py
  rotkehlchen/chain/aggregator.py
  rotkehlchen/chain/ethereum/etherscan.py
  rotkehlchen/chain/ethereum/modules/eth2/constants.py
  rotkehlchen/chain/ethereum/modules/eth2/eth2.py
  rotkehlchen/db/cache.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/updates.py
  rotkehlchen/db/upgrades/v40_v41.py
  rotkehlchen/exchanges/bitstamp.py
  rotkehlchen/exchanges/coinbase.py
  rotkehlchen/externalapis/beaconchain/service.py
  rotkehlchen/externalapis/blockscout.py
  rotkehlchen/premium/sync.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tasks/events.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tasks/utils.py
  rotkehlchen/tests/api/test_periodic.py
  rotkehlchen/tests/api/test_users.py
  rotkehlchen/tests/data/data_migration_v0.db
  rotkehlchen/tests/data/v40_rotkehlchen.db
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/integration/test_eth2.py
  rotkehlchen/tests/integration/test_premium.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7221 refactor: migrate assets balances table to table from lib
  frontend/app/package.json
  frontend/app/src/components/AssetBalances.vue
  frontend/app/src/components/EvmNativeTokenBreakdown.vue
  frontend/app/src/components/accounts/manual-balances/ManualBalanceTable.vue
  frontend/app/src/components/asset-manager/newly-detected/NewlyDetectedAssetTable.vue
  frontend/app/src/components/dashboard/DashboardAssetTable.vue
  frontend/app/src/components/dashboard/NftBalanceTable.vue
  frontend/app/src/components/defi/yearn/YearnAssetsTable.vue
  frontend/app/src/pages/balances/blockchain/index.vue
  frontend/app/src/pages/balances/exchange/index.vue
  frontend/app/src/types/blockchain/accounts.ts
  frontend/app/src/utils/balances.ts
  frontend/app/tests/unit/specs/components/evm-native-token-breakdown.spec.ts
  frontend/app/tests/unit/specs/components/settings/asset-balances.spec.ts
  frontend/app/tests/unit/utils/provide-defaults.ts
  frontend/pnpm-lock.yaml
Labels: ready for final review

#7235 fix (#7176): add label for addresses in CSV export
  docs/changelog.rst
  rotkehlchen/accounting/export/csv.py
  rotkehlchen/accounting/structures/processed_event.py
  rotkehlchen/chain/evm/constants.py
  rotkehlchen/tests/api/test_pnl_csv.py
  rotkehlchen/tests/unit/test_evm_misc.py
Labels: ready for final review

#7241 chore: integrate table defaults to store and app setup.
  frontend/app/package.json
  frontend/app/src/components/helper/DataTable.vue
  frontend/app/src/main.ts
  frontend/app/src/plugins/rui/index.ts
  frontend/app/src/store/settings/frontend.ts
  frontend/app/tests/unit/specs/components/defi/wizard/module-selector.spec.ts
  frontend/app/tests/unit/specs/pages/settings/user-security-settings.spec.ts
  frontend/pnpm-lock.yaml
Labels: ready for final review

#7242 chore (cache): add kwargs annotations
  rotkehlchen/db/cache.py
  rotkehlchen/db/dbhandler.py
Labels: ready for final review

#7251 Add entry type mappings
  docs/api.rst
  rotkehlchen/accounting/constants.py
  rotkehlchen/accounting/entry_type_mappings.py
  rotkehlchen/api/rest.py
  rotkehlchen/history/events/structures/types.py
  rotkehlchen/tests/api/test_misc.py
Labels: ready for final review

#7252 Update behaviour of spam tokens
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/server.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/globaldb/cache.py
  rotkehlchen/globaldb/utils.py
  rotkehlchen/tests/api/test_assets.py
Labels: ready for final review

#7253 Fix price queries with defillama
  docs/changelog.rst
  rotkehlchen/constants/misc.py
  rotkehlchen/externalapis/defillama.py
  rotkehlchen/inquirer.py
  rotkehlchen/tests/unit/test_inquirer.py
Labels: ready for final review

#7264 feat (paraswap): add decoder
  rotkehlchen/chain/ethereum/modules/paraswap/__init__.py
  rotkehlchen/chain/ethereum/modules/paraswap/constants.py
  rotkehlchen/chain/ethereum/modules/paraswap/decoder.py
  rotkehlchen/chain/ethereum/modules/uniswap/v3/constants.py
  rotkehlchen/chain/evm/decoding/paraswap/__init__.py
  rotkehlchen/chain/evm/decoding/paraswap/constants.py
  rotkehlchen/chain/evm/decoding/paraswap/decoder.py
  rotkehlchen/tests/unit/accounting/evm/test_paraswap.py
  rotkehlchen/tests/unit/decoders/test_main.py
  rotkehlchen/tests/unit/decoders/test_paraswap.py
Labels: PR review work

#7222 Make oracle penalty settings user-modifiable at the backend
  docs/api.rst
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/settings.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/api/test_settings.py
  rotkehlchen/tests/data/pnl_debug.json
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/fixtures/rotkehlchen.py
  rotkehlchen/tests/unit/test_inquirer.py
  rotkehlchen/utils/mixins/penalizable_oracle.py
Labels: ready for final review

#7302 Fix managed assets table column width
  frontend/app/package.json
  frontend/app/src/components/asset-manager/managed/ManagedAssetTable.vue
  frontend/pnpm-lock.yaml
Labels: ready for peer review

#7293 Fix (accounting): order of processed fee events
  rotkehlchen/accounting/history_base_entries.py
  rotkehlchen/accounting/pot.py
  rotkehlchen/tests/unit/accounting/evm/test_paraswap.py
  rotkehlchen/tests/utils/accounting.py
Labels: ready for final review

#7304 Update: docs for pnl, history events, defi vaults
  docs/images/events_query_process.png
  docs/images/events_query_process_export.png
  docs/images/sc_pnl_export_debug_data.png
  docs/images/sc_pnl_missing_acquisitions.png
  docs/images/sc_pnl_missing_prices.png
  docs/images/sc_pnl_report.png
  docs/images/sc_pnl_report1.png
  docs/images/sc_pnl_report2.png
  docs/images/sc_pnl_reports_costbasis.png
  docs/images/sc_pnl_saved_reports.png
  docs/images/vaults_premium_demo.gif
  docs/images/vaults_premium_demo1.png
  docs/images/vaults_premium_demo2.png
  docs/images/vaults_premium_demo3.png
  docs/images/vaults_premium_demo4.png
  docs/usage_guide.rst
Labels: ready for peer review

#7310 Feat (paraswap): curve, balancer, and uniswapV2_buy support
  rotkehlchen/chain/evm/decoding/paraswap/decoder.py
  rotkehlchen/tests/unit/decoders/test_paraswap.py
Labels: ready for final review

#7309 Add initial GMX V1 support
  frontend/app/public/assets/images/protocols/gmx.svg
  rotkehlchen/chain/arbitrum_one/modules/gmx/__init__.py
  rotkehlchen/chain/arbitrum_one/modules/gmx/constants.py
  rotkehlchen/chain/arbitrum_one/modules/gmx/decoder.py
  rotkehlchen/constants/assets.py
  rotkehlchen/tests/unit/decoders/test_gmx.py
Labels: ready for final review

#7318 Feat (Paraswap): Add multichain support
  docs/changelog.rst
  rotkehlchen/chain/arbitrum_one/modules/paraswap/__init__.py
  rotkehlchen/chain/arbitrum_one/modules/paraswap/constants.py
  rotkehlchen/chain/arbitrum_one/modules/paraswap/decoder.py
  rotkehlchen/chain/base/modules/paraswap/__init__.py
  rotkehlchen/chain/base/modules/paraswap/constants.py
  rotkehlchen/chain/base/modules/paraswap/decoder.py
  rotkehlchen/chain/evm/decoding/paraswap/decoder.py
  rotkehlchen/chain/optimism/modules/paraswap/__init__.py
  rotkehlchen/chain/optimism/modules/paraswap/decoder.py
  rotkehlchen/chain/polygon_pos/modules/paraswap/__init__.py
  rotkehlchen/chain/polygon_pos/modules/paraswap/constants.py
  rotkehlchen/chain/polygon_pos/modules/paraswap/decoder.py
  rotkehlchen/tests/unit/decoders/test_paraswap.py
Labels: ready for final review

#7329 Change invalid premium key error status code
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/tests/api/test_users.py
Labels: ready for final review

#7326 Add support for socket
  docs/changelog.rst
  frontend/app/public/assets/images/protocols/socket.png
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/chain/evm/decoding/socket_bridge/__init__.py
  rotkehlchen/chain/evm/decoding/socket_bridge/constants.py
  rotkehlchen/chain/evm/decoding/socket_bridge/decoder.py
  rotkehlchen/tests/unit/decoders/test_main.py
  rotkehlchen/tests/unit/decoders/test_socket.py
Labels: ready for final review

#7333 Fix decoding of WETH in uniswap v3
  rotkehlchen/chain/ethereum/modules/uniswap/v3/decoder.py
  rotkehlchen/tests/unit/decoders/test_uniswapv3.py
Labels: ready for final review

#7332 Fix max queried range in bybit
  rotkehlchen/exchanges/bybit.py
  rotkehlchen/tests/exchanges/test_bybit.py
Labels: PR review work

#7343 fix (cache): LAST_SPAM_ASSETS_DETECT_KEY usage
  rotkehlchen/tasks/assets.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for peer review

#7340 Notify user on fatal error during report
  docs/api.rst
  rotkehlchen/accounting/accountant.py
  rotkehlchen/accounting/cost_basis/base.py
  rotkehlchen/api/rest.py
  rotkehlchen/errors/misc.py
  rotkehlchen/tests/api/test_history.py
Labels: ready for final review

#7330 Feat (7018): Move account labels to address_book
  docs/changelog.rst
  rotkehlchen/accounting/structures/processed_event.py
  rotkehlchen/chain/evm/names.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/minimized_schema.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/upgrades/v40_v41.py
  rotkehlchen/tests/api/test_addressbook.py
  rotkehlchen/tests/api/test_makerdao_dsr.py
  rotkehlchen/tests/data/data_migration_v0.db
  rotkehlchen/tests/data/v40_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
Labels: ready for final review

#7345 Add paraswap case with factories
  rotkehlchen/chain/evm/decoding/paraswap/constants.py
  rotkehlchen/chain/evm/decoding/paraswap/decoder.py
  rotkehlchen/tests/unit/decoders/test_paraswap.py
Labels: ready for final review

#7346 Feat (userdb): Reset history_events in upgrade v41
  rotkehlchen/db/upgrades/v40_v41.py
  rotkehlchen/tests/data/v40_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
Labels: ready for final review

#7347 Avoid executing eth only tasks if no address is tracked
  rotkehlchen/tasks/manager.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7356 Update addressbook to work with any blockchain
  docs/api.rst
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/addressbook.py
  rotkehlchen/tests/api/test_addressbook.py
  rotkehlchen/tests/utils/factories.py
  rotkehlchen/types.py
Labels: PR review work

#7351 Remove bittrex credentials from database
  rotkehlchen/db/upgrades/v40_v41.py
  rotkehlchen/tests/data/v40_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
Labels: ready for final review

#7355 Feat (import): Add CSV import for Kucoin trades
  docs/api.rst
  docs/changelog.rst
  rotkehlchen/data_import/importers/kucoin.py
  rotkehlchen/data_import/manager.py
  rotkehlchen/tests/api/test_data_import.py
  rotkehlchen/tests/data/kucoin_order_history.csv
  rotkehlchen/tests/data/kucoin_order_history_old.csv
  rotkehlchen/tests/utils/dataimport.py
Labels: ready for final review
