Repository rotki/rotki, pull requests merged in 2024-04, with the labels that each got.

#7696 Feat (API): Allow sorting in addressbook
  docs/api.rst
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/filtering.py
  rotkehlchen/tests/api/test_addressbook.py
Labels: ready for final review

#7710 Feat (Aave): Support v3 in Defi sections
  docs/changelog.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/chain/ethereum/modules/aave/aave.py
  rotkehlchen/tests/api/test_aave.py
  rotkehlchen/tests/unit/test_aave.py
Labels: ready for final review

#7718 Fix (test_query_aave_balances): Remove flakiness
  rotkehlchen/tests/api/test_aave.py
Labels: ready for peer review

#7749 Remove 'manualcurrent' from price oracles
  rotkehlchen/db/upgrades/v41_v42.py
  rotkehlchen/inquirer.py
  rotkehlchen/oracles/structures.py
  rotkehlchen/tests/data/v41_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
Labels: ready for final review

#7752 fix: update snapshot edit form
  frontend/app/package.json
  frontend/app/src/components/dashboard/SnapshotActionButton.vue
  frontend/app/src/components/dashboard/edit-snapshot/EditBalancesSnapshotForm.vue
  frontend/app/src/components/dashboard/edit-snapshot/EditBalancesSnapshotLocationSelector.vue
  frontend/app/src/components/helper/LocationSelector.vue
  frontend/app/src/locales/en.json
  frontend/pnpm-lock.yaml
Labels: frontend

#7770 Allow to filter by symbol
  docs/api.rst
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/filtering.py
  rotkehlchen/tests/api/test_location_asset_mappings.py
Labels: ready for final review

#7763 Fix (Aave): Not notify when detecting v3 tokens
  rotkehlchen/assets/utils.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7772 Add setting to delete past calendar events
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/cache.py
  rotkehlchen/db/calendar.py
  rotkehlchen/db/minimized_schema.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/settings.py
  rotkehlchen/db/upgrades/v41_v42.py
  rotkehlchen/tasks/calendar.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tasks/utils.py
  rotkehlchen/tests/api/test_calendar.py
  rotkehlchen/tests/data/pnl_debug.json
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7778 style: some UI improvement
  frontend/app/src/components/dashboard/SnapshotImportDialog.vue
  frontend/app/src/components/dialogs/ConfirmDialog.vue
  frontend/app/src/components/helper/PrioritizedList.vue
  frontend/app/src/components/history/events/HistoryEventNote.vue
  frontend/app/src/components/history/events/HistoryEventsList.vue
  frontend/app/src/components/history/events/HistoryEventsListTable.vue
  frontend/app/src/components/history/events/HistoryEventsView.vue
  frontend/app/src/components/nft/NftSorter.vue
  frontend/app/src/components/settings/accounting/rule/AccountingRuleSetting.vue
  frontend/app/src/components/settings/explorers/Explorers.vue
  frontend/app/src/components/settings/general/nft/NftImageRenderingSetting.vue
  frontend/app/src/locales/en.json
Labels: frontend

#7775 Remove code related to balancer events
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/server.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/chain/ethereum/modules/balancer/__init__.py
  rotkehlchen/chain/ethereum/modules/balancer/balancer.py
  rotkehlchen/chain/ethereum/modules/balancer/db.py
  rotkehlchen/chain/ethereum/modules/balancer/graph.py
  rotkehlchen/chain/ethereum/modules/balancer/types.py
  rotkehlchen/chain/ethereum/modules/balancer/utils.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/minimized_schema.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/upgrades/v41_v42.py
  rotkehlchen/serialization/serialize.py
  rotkehlchen/tests/api/test_balancer.py
  rotkehlchen/tests/data/v41_rotkehlchen.db
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/db/test_locations.py
Labels: ready for final review

#7781 Adjust behaviour of task in the calendar
  rotkehlchen/tasks/calendar.py
  rotkehlchen/tasks/manager.py
Labels: ready for final review

#7779 Remove graph events for yearn
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/server.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/chain/ethereum/modules/yearn/constants.py
  rotkehlchen/chain/ethereum/modules/yearn/db.py
  rotkehlchen/chain/ethereum/modules/yearn/graph.py
  rotkehlchen/chain/ethereum/modules/yearn/structures.py
  rotkehlchen/chain/ethereum/modules/yearn/vaults.py
  rotkehlchen/chain/ethereum/modules/yearn/vaultsv2.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/minimized_schema.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/upgrades/v41_v42.py
  rotkehlchen/serialization/serialize.py
  rotkehlchen/tests/api/test_yearn_vaults.py
  rotkehlchen/tests/data/v41_rotkehlchen.db
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/db/test_defi_events.py
  rotkehlchen/tests/fixtures/__init__.py
  rotkehlchen/tests/fixtures/contracts.py
Labels: ready for final review

#7800 Query blockscout instead of the graph for ts to block
  rotkehlchen/chain/ethereum/node_inquirer.py
  rotkehlchen/chain/evm/node_inquirer.py
  rotkehlchen/externalapis/blockscout.py
  rotkehlchen/tests/unit/test_ethereum_inquirer.py
Labels: ready for final review

#7783 Feat (Calendar): Reminders for ENS expiry
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/chain/ethereum/modules/ens/decoder.py
  rotkehlchen/db/cache.py
  rotkehlchen/db/calendar.py
  rotkehlchen/db/settings.py
  rotkehlchen/tasks/calendar.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tasks/utils.py
  rotkehlchen/tests/data/pnl_debug.json
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/unit/decoders/test_ens.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7812 Ensure consistency for number of pending tx to decode
  rotkehlchen/api/rest.py
  rotkehlchen/tests/api/test_evmlike.py
Labels: ready for final review

#7814 Fix balancer trades of token to token
  rotkehlchen/chain/ethereum/modules/balancer/v2/decoder.py
  rotkehlchen/tests/unit/decoders/test_balancer.py
Labels: ready for final review

#7822 style: fix wrong notification color
  frontend/app/src/components/dialogs/ConfirmDialog.vue
  frontend/app/src/components/history/MovementLinks.vue
  frontend/app/src/components/status/notifications/Notification.vue
  frontend/app/src/components/status/notifications/PendingTask.vue
  frontend/app/src/composables/price-manager/latest/index.ts
  frontend/app/src/main.scss
Labels: frontend

#7821 fix: properly load NFT if the URL is video
  frontend/app/src/auto-imports.d.ts
  frontend/app/src/components/helper/NftDetails.vue
  frontend/app/src/components/nft/NftGalleryItem.vue
  frontend/app/src/composables/nft-image.ts
  frontend/app/src/utils/nft.ts
Labels: frontend

#7824 Add handling for GRT delegation transfer events to L2
  rotkehlchen/chain/ethereum/modules/thegraph/constants.py
  rotkehlchen/chain/evm/decoding/thegraph/decoder.py
  rotkehlchen/tests/unit/decoders/test_thegraph.py
Labels: ready for final review

#7833 fix(frontend): remove unneeded error on version update check setting
  frontend/app/src/components/settings/explorers/Explorers.vue
  frontend/app/src/components/settings/frontend/AnimationsEnabledSetting.vue
  frontend/app/src/components/settings/general/DateDisplayFormatSetting.vue
  frontend/app/src/components/settings/general/DateInputFormatSetting.vue
  frontend/app/src/components/settings/general/DisplayDateInLocaltimeSetting.vue
  frontend/app/src/components/settings/general/EvmChainsToIgnoreSettings.vue
  frontend/app/src/components/settings/general/TreatEthAsEth2Setting.vue
  frontend/app/src/components/settings/general/UsageAnalyticsSetting.vue
  frontend/app/src/components/settings/general/VersionUpdateFrequencySetting.vue
  frontend/app/src/composables/message-handling.ts
  frontend/app/src/pages/settings/general/index.vue
Labels: frontend

#7842 Fix (Calendar): Update last entry for same ENS
  docs/changelog.rst
  rotkehlchen/tasks/calendar.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: ready for final review

#7859 fix: lazy loader debounced when appearing
  frontend/app/src/components/helper/LazyLoader.vue
  frontend/app/src/components/history/events/HistoryEventsListTable.vue
Labels: frontend, ready for final review

#7864 fix(frontend): fix chain sent on tx delete, use chain id and handle notification
  frontend/app/src/components/history/events/HistoryEventsAction.vue
  frontend/app/src/components/history/events/HistoryEventsView.vue
  frontend/app/src/composables/info/chains.ts
  frontend/app/src/locales/cn.json
  frontend/app/src/locales/en.json
  frontend/app/src/locales/es.json
  frontend/app/src/locales/fr.json
  frontend/app/src/locales/gr.json
Labels: frontend
