Repository rotki/rotki, pull requests merged in 2024-06, with the labels that each got.

#8025 Fix wrong order for nfts
  docs/changelog.rst
  frontend/app/src/components/accounts/balances/NonFungibleBalances.vue
  frontend/app/src/components/dashboard/NftBalanceTable.vue
  frontend/app/src/types/nfbalances.ts
  rotkehlchen/chain/ethereum/modules/nft/nfts.py
  rotkehlchen/db/minimized_schema.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/settings.py
  rotkehlchen/db/upgrade_manager.py
  rotkehlchen/db/upgrades/v42_v43.py
  rotkehlchen/tests/data/v42_rotkehlchen.db
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/unit/test_nfts.py
Labels: ready for final review

#8024 Chore (Curve): Move multichain logic to EVM
  rotkehlchen/api/rest.py
  rotkehlchen/chain/ethereum/manager.py
  rotkehlchen/chain/ethereum/modules/convex/convex_cache.py
  rotkehlchen/chain/ethereum/modules/curve/accountant.py
  rotkehlchen/chain/ethereum/modules/curve/balances.py
  rotkehlchen/chain/ethereum/modules/curve/constants.py
  rotkehlchen/chain/ethereum/modules/curve/curve_cache.py
  rotkehlchen/chain/ethereum/modules/curve/decoder.py
  rotkehlchen/chain/ethereum/modules/eth2/decoder.py
  rotkehlchen/chain/evm/decoding/curve/__init__.py
  rotkehlchen/chain/evm/decoding/curve/constants.py
  rotkehlchen/chain/evm/decoding/curve/curve_cache.py
  rotkehlchen/chain/evm/decoding/curve/decoder.py
  rotkehlchen/chain/evm/decoding/gearbox/gearbox_cache.py
  rotkehlchen/chain/evm/decoding/interfaces.py
  rotkehlchen/chain/evm/decoding/velodrome/decoder.py
  rotkehlchen/chain/evm/decoding/velodrome/velodrome_cache.py
  rotkehlchen/chain/evm/node_inquirer.py
  rotkehlchen/globaldb/cache.py
  rotkehlchen/inquirer.py
  rotkehlchen/tests/api/test_calendar.py
  rotkehlchen/tests/api/test_ethereum_transactions.py
  rotkehlchen/tests/api/test_misc.py
  rotkehlchen/tests/unit/accounting/evm/test_curve.py
  rotkehlchen/tests/unit/decoders/test_curve.py
  rotkehlchen/tests/unit/globaldb/test_globaldb_cache.py
  rotkehlchen/tests/unit/test_inquirer.py
Labels: ready for final review

#8035 Feat (Balances): Auto-detect tokens
  docs/changelog.rst
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/db/history_events.py
  rotkehlchen/db/settings.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tests/data/pnl_debug.json
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/unit/test_tasks_manager.py
Labels: PR review work

#8050 Fix duplicate entries in globaldb conflicts
  docs/changelog.rst
  rotkehlchen/globaldb/updates.py
  rotkehlchen/tests/unit/globaldb/test_asset_updates.py
Labels: ready for final review

#8063 feat(gearbox): decode staking events for Gear
  rotkehlchen/chain/arbitrum_one/modules/gearbox/constants.py
  rotkehlchen/chain/arbitrum_one/modules/gearbox/decoder.py
  rotkehlchen/chain/ethereum/modules/gearbox/constants.py
  rotkehlchen/chain/ethereum/modules/gearbox/decoder.py
  rotkehlchen/chain/evm/decoding/gearbox/constants.py
  rotkehlchen/chain/evm/decoding/gearbox/decoder.py
  rotkehlchen/chain/optimism/modules/gearbox/constants.py
  rotkehlchen/chain/optimism/modules/gearbox/decoder.py
  rotkehlchen/tests/unit/decoders/test_gearbox.py
Labels: ready for final review

#8081 feat(hop): add Hop ARB reward contract
  rotkehlchen/chain/arbitrum_one/modules/hop/constants.py
  rotkehlchen/tests/unit/decoders/test_hop.py
  rotkehlchen/tests/unit/test_protocol_balances.py
Labels: ready for peer review

#8073 Add huobi balances
  frontend/app/public/assets/images/protocols/htx.svg
  rotkehlchen/assets/converters.py
  rotkehlchen/constants/location_details.py
  rotkehlchen/db/schema.py
  rotkehlchen/db/upgrades/v42_v43.py
  rotkehlchen/exchanges/constants.py
  rotkehlchen/exchanges/htx.py
  rotkehlchen/tests/api/test_exchanges.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/exchanges/test_htx.py
  rotkehlchen/tests/fixtures/exchanges/__init__.py
  rotkehlchen/tests/fixtures/exchanges/htx.py
  rotkehlchen/tests/utils/exchanges.py
  rotkehlchen/types.py
Labels: ready for final review

#8114 Feat (Curve): Detect prices of LP and Gauge tokens
  docs/changelog.rst
  rotkehlchen/api/rest.py
  rotkehlchen/chain/arbitrum_one/manager.py
  rotkehlchen/chain/arbitrum_one/node_inquirer.py
  rotkehlchen/chain/base/manager.py
  rotkehlchen/chain/base/node_inquirer.py
  rotkehlchen/chain/ethereum/manager.py
  rotkehlchen/chain/evm/decoding/curve/constants.py
  rotkehlchen/chain/evm/decoding/curve/curve_cache.py
  rotkehlchen/chain/evm/decoding/interfaces.py
  rotkehlchen/chain/evm/l2_with_l1_fees/node_inquirer.py
  rotkehlchen/chain/evm/manager.py
  rotkehlchen/chain/evm/node_inquirer.py
  rotkehlchen/chain/gnosis/manager.py
  rotkehlchen/chain/gnosis/node_inquirer.py
  rotkehlchen/chain/optimism/manager.py
  rotkehlchen/chain/polygon_pos/manager.py
  rotkehlchen/chain/polygon_pos/node_inquirer.py
  rotkehlchen/chain/scroll/manager.py
  rotkehlchen/chain/scroll/node_inquirer.py
  rotkehlchen/inquirer.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/unit/globaldb/test_globaldb_cache.py
  rotkehlchen/tests/unit/test_evm_misc.py
  rotkehlchen/tests/unit/test_inquirer.py
  rotkehlchen/utils/mixins/lockable.py
Labels: PR review work

#8136 Use beaconchain api for daily stats
  rotkehlchen/chain/ethereum/modules/eth2/beacon.py
  rotkehlchen/chain/ethereum/modules/eth2/eth2.py
  rotkehlchen/chain/ethereum/modules/eth2/utils.py
  rotkehlchen/db/upgrades/v35_v36.py
  rotkehlchen/externalapis/beaconchain/service.py
  rotkehlchen/tests/api/test_eth2.py
  rotkehlchen/tests/data/mocks/test_eth2/validator_daily_stats/33710.html
  rotkehlchen/tests/data/mocks/test_eth2/validator_daily_stats/33710.json
  rotkehlchen/tests/data/mocks/test_eth2/validator_daily_stats/999.html
  rotkehlchen/tests/data/mocks/test_eth2/validator_daily_stats/999.json
  rotkehlchen/tests/unit/test_eth2.py
  rotkehlchen/utils/misc.py
Labels: ready for final review

#8140 Fix balances for validators
  docs/changelog.rst
  rotkehlchen/chain/aggregator.py
  rotkehlchen/tests/api/test_eth2.py
Labels: ready for final review

#8155 fix(decoder): simplify liquidity decoding in Hop
  rotkehlchen/chain/evm/decoding/hop/decoder.py
  rotkehlchen/tests/unit/decoders/test_hop.py
Labels: ready for final review

#8156 refactor(tests): update HTX mock to handle option checks
  rotkehlchen/tests/exchanges/test_htx.py
Labels: ready for final review

#8159 Chore (tests): Unload protocol's cache by default
  rotkehlchen/chain/evm/decoding/interfaces.py
  rotkehlchen/tests/fixtures/blockchain.py
  rotkehlchen/tests/fixtures/globaldb.py
  rotkehlchen/tests/unit/decoders/test_aerodrome.py
  rotkehlchen/tests/unit/decoders/test_convex.py
  rotkehlchen/tests/unit/decoders/test_curve.py
  rotkehlchen/tests/unit/decoders/test_gearbox.py
  rotkehlchen/tests/unit/decoders/test_velodrome.py
  rotkehlchen/tests/unit/test_evm_balances.py
  rotkehlchen/tests/unit/test_protocol_balances.py
  rotkehlchen/tests/utils/decoders.py
  rotkehlchen/tests/utils/ethereum.py
Labels: ready for final review

#8165 Correctly calculate PnL for validators when exiting
  docs/changelog.rst
  rotkehlchen/history/events/structures/eth2.py
  rotkehlchen/tests/api/test_settings.py
  rotkehlchen/tests/unit/accounting/test_staking.py
Labels: ready for final review

#8166 Feat (Cache): Notify refresh progress
  docs/websockets.rst
  rotkehlchen/api/websockets/notifier.py
  rotkehlchen/api/websockets/typedefs.py
  rotkehlchen/chain/ethereum/defi/defisaver_proxy.py
  rotkehlchen/chain/ethereum/defi/zerionsdk.py
  rotkehlchen/chain/ethereum/interfaces/ammswap/ammswap.py
  rotkehlchen/chain/ethereum/modules/aave/aave.py
  rotkehlchen/chain/ethereum/modules/balancer/balancer.py
  rotkehlchen/chain/ethereum/modules/convex/convex_cache.py
  rotkehlchen/chain/ethereum/modules/l2/loopring.py
  rotkehlchen/chain/ethereum/modules/liquity/trove.py
  rotkehlchen/chain/ethereum/modules/makerdao/dsr.py
  rotkehlchen/chain/ethereum/modules/makerdao/vaults.py
  rotkehlchen/chain/ethereum/modules/pickle_finance/main.py
  rotkehlchen/chain/ethereum/modules/yearn/vaults.py
  rotkehlchen/chain/ethereum/modules/yearn/vaultsv2.py
  rotkehlchen/chain/evm/decoding/curve/curve_cache.py
  rotkehlchen/chain/evm/decoding/gearbox/gearbox_cache.py
  rotkehlchen/chain/evm/decoding/hop/decoder.py
  rotkehlchen/chain/evm/decoding/interfaces.py
  rotkehlchen/chain/evm/decoding/velodrome/velodrome_cache.py
  rotkehlchen/chain/evm/node_inquirer.py
  rotkehlchen/chain/evm/utils.py
  rotkehlchen/db/settings.py
  rotkehlchen/exchanges/data_structures.py
  rotkehlchen/exchanges/kraken.py
  rotkehlchen/history/price.py
  rotkehlchen/serialization/serialize.py
  rotkehlchen/tests/unit/globaldb/test_globaldb_cache.py
  rotkehlchen/tests/utils/decoders.py
  rotkehlchen/user_messages.py
Labels: ready for final review

#8178 Query monerium on re-decode
  rotkehlchen/api/rest.py
  rotkehlchen/externalapis/monerium.py
  rotkehlchen/tasks/manager.py
  rotkehlchen/tests/external_apis/test_monerium.py
Labels: ready for final review

#8193 Refactor (Exchanges): Purge coinbasepro
  Makefile
  docs/changelog.rst
  docs/usage_guide.rst
  rotkehlchen/db/upgrades/v42_v43.py
  rotkehlchen/exchanges/coinbasepro.py
  rotkehlchen/exchanges/constants.py
  rotkehlchen/exchanges/okx.py
  rotkehlchen/tests/api/test_exchanges.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/exchanges/test_coinbasepro.py
  rotkehlchen/tests/fixtures/exchanges/__init__.py
  rotkehlchen/tests/fixtures/exchanges/coinbasepro.py
  rotkehlchen/tests/fixtures/variables.py
  rotkehlchen/tests/utils/exchanges.py
Labels: ready for final review
