Repository rotki/rotki, pull requests merged in 2024-08, with the labels that each got.

#8349 Raise error on bad underlying tokens
  rotkehlchen/chain/evm/decoding/gearbox/gearbox_cache.py
  rotkehlchen/globaldb/handler.py
  rotkehlchen/inquirer.py
  rotkehlchen/tests/unit/globaldb/test_globaldb.py
  rotkehlchen/tests/unit/test_inquirer.py
Labels: ready for final review

#8351 Manage multichain addresses
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/server.py
  rotkehlchen/api/v1/fields.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/chain/bitcoin/xpub.py
  rotkehlchen/db/addressbook.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/db/utils.py
  rotkehlchen/rotkehlchen.py
  rotkehlchen/tests/api/blockchain/test_base.py
  rotkehlchen/tests/api/test_addressbook.py
  rotkehlchen/tests/api/test_metadata.py
  rotkehlchen/tests/api/test_tags.py
  rotkehlchen/tests/db/test_xpubs.py
  rotkehlchen/tests/utils/factories.py
  rotkehlchen/tests/utils/xpubs.py
  rotkehlchen/types.py
Labels: ready for final review

#8363 Chore (Migrations): Add 16th migration
  rotkehlchen/data_migrations/manager.py
  rotkehlchen/data_migrations/migrations/migrations_16.py
  rotkehlchen/tests/data_migrations/test_migrations.py
Labels: ready for peer review, ready for final review

#8370 Improve spammed account detection
  docs/changelog.rst
  rotkehlchen/chain/evm/transactions.py
  rotkehlchen/tests/unit/test_chains_aggregator.py
Labels: ready for final review

#8384 Fix (LAST_DATA_MIGRATION): Update to 16
  rotkehlchen/data_migrations/constants.py
  rotkehlchen/tests/data_migrations/test_migrations.py
Labels: ready for final review

#8396 Add decoding of zksync lite withdrawals
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/zksync/decoder.py
  rotkehlchen/tests/unit/decoders/test_zksync.py
Labels: ready for final review

#8423 Accept a list when adding spam tokens
  docs/api.rst
  rotkehlchen/api/rest.py
  rotkehlchen/api/v1/resources.py
  rotkehlchen/api/v1/schemas.py
  rotkehlchen/data_handler.py
  rotkehlchen/tests/api/test_assets.py
Labels: ready for final review

#8425 Add LlamaZip swap decoder
  docs/changelog.rst
  frontend/app/public/assets/images/protocols/llamazip.png
  rotkehlchen/chain/arbitrum_one/modules/llamazip/__init__.py
  rotkehlchen/chain/arbitrum_one/modules/llamazip/decoder.py
  rotkehlchen/chain/evm/decoding/llamazip/__init__.py
  rotkehlchen/chain/evm/decoding/llamazip/constants.py
  rotkehlchen/chain/evm/decoding/llamazip/decoder.py
  rotkehlchen/chain/optimism/modules/llamazip/__init__.py
  rotkehlchen/chain/optimism/modules/llamazip/decoder.py
  rotkehlchen/tests/unit/decoders/test_llamazip.py
Labels: ready for final review

#8421 Fix (Nightlies): Cleanups for windows
  rotkehlchen/db/dbhandler.py
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/db/test_db_upgrades.py
  rotkehlchen/tests/db/test_evmtx.py
  rotkehlchen/tests/db/test_xpubs.py
  rotkehlchen/tests/fixtures/accounting.py
  rotkehlchen/tests/fixtures/rotkehlchen.py
  rotkehlchen/tests/test_users.py
  rotkehlchen/tests/unit/globaldb/test_upgrades.py
  rotkehlchen/tests/unit/test_blockchain_balances.py
Labels: ready for final review

#8432 Add decoding of Optimism DAI bridging
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/optimism_bridge/decoder.py
  rotkehlchen/chain/optimism/modules/optimism_bridge/decoder.py
  rotkehlchen/tests/unit/decoders/test_optimism_bridge.py
Labels: ready for final review

#8409 Feat (Aave): Decode interests separately
  docs/changelog.rst
  frontend/app/src/plugins/rui/index.ts
  rotkehlchen/accounting/constants.py
  rotkehlchen/chain/evm/decoding/aave/v3/decoder.py
  rotkehlchen/history/events/structures/types.py
  rotkehlchen/tests/unit/decoders/test_aave_v3.py
Labels: ready for final review

#8417 Handle params for external services better
  rotkehlchen/externalapis/blockscout.py
  rotkehlchen/externalapis/coingecko.py
  rotkehlchen/externalapis/cryptocompare.py
  rotkehlchen/externalapis/defillama.py
  rotkehlchen/tests/external_apis/test_coingecko.py
Labels: ready for final review

#8443 Support Blockpit CSV imports
  docs/api.rst
  docs/changelog.rst
  frontend/app/public/assets/images/protocols/blockpit.png
  frontend/app/src/components/import/BlockpitImport.vue
  frontend/app/src/components/import/GroupedImport.vue
  frontend/app/src/locales/en.json
  frontend/app/src/types/upload-types.ts
  rotkehlchen/data_import/importers/blockpit.py
  rotkehlchen/data_import/importers/cointracking.py
  rotkehlchen/data_import/importers/constants.py
  rotkehlchen/data_import/manager.py
  rotkehlchen/data_import/utils.py
  rotkehlchen/tests/api/test_data_import.py
  rotkehlchen/tests/data/blockpit_transactions.csv
  rotkehlchen/tests/utils/dataimport.py
Labels: ready for final review

#8446 Chore (Polygon): Post hard-fork MATIC prices
  rotkehlchen/chain/polygon_pos/constants.py
  rotkehlchen/history/price.py
  rotkehlchen/inquirer.py
  rotkehlchen/tests/unit/globaldb/test_prices.py
  rotkehlchen/tests/unit/test_inquirer.py
Labels: ready for final review

#8457 add extrafi for optimism
  frontend/app/public/assets/images/protocols/extrafi.svg
  rotkehlchen/chain/optimism/modules/extrafi/__init__.py
  rotkehlchen/chain/optimism/modules/extrafi/constants.py
  rotkehlchen/chain/optimism/modules/extrafi/decoder.py
  rotkehlchen/tests/unit/decoders/test_extrafi.py
Labels: ready for final review

#8450 Feat (DB Writer): Use protobuf instead of pickle
  rotkehlchen/db/drivers/client.py
  rotkehlchen/db/drivers/db_messages.proto
  rotkehlchen/db/drivers/db_messages_pb2.py
  rotkehlchen/db/drivers/server.py
  rotkehlchen/fval.py
Labels: ready for peer review

#8466 Monerium fixes
  docs/changelog.rst
  rotkehlchen/chain/ethereum/modules/monerium/decoder.py
  rotkehlchen/chain/evm/decoding/decoder.py
  rotkehlchen/chain/evm/decoding/monerium/decoder.py
  rotkehlchen/chain/evm/tokens.py
  rotkehlchen/chain/gnosis/decoding/decoder.py
  rotkehlchen/chain/gnosis/modules/monerium/constants.py
  rotkehlchen/chain/gnosis/modules/monerium/decoder.py
  rotkehlchen/chain/gnosis/tokens.py
  rotkehlchen/chain/polygon_pos/decoding/decoder.py
  rotkehlchen/chain/polygon_pos/modules/monerium/constants.py
  rotkehlchen/chain/polygon_pos/modules/monerium/decoder.py
  rotkehlchen/chain/polygon_pos/tokens.py
  rotkehlchen/db/dbhandler.py
  rotkehlchen/tasks/assets.py
  rotkehlchen/tests/db/test_db.py
  rotkehlchen/tests/unit/decoders/test_curve.py
  rotkehlchen/tests/unit/decoders/test_monerium.py
  rotkehlchen/tests/unit/test_tasks_manager.py
  rotkehlchen/tests/unit/test_tokens.py
Labels: PR review work
